/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package doug;

/**
 *
 * @author DouglasFerreirag
 */




public class AlteraPessoa extends javax.swing.JFrame {

    /**
     * Creates new form ModificaPessoa
     */
    
    private String alterado = "";
  
    private boolean trava;
    
    public AlteraPessoa() {
        initComponents();
       
        this.setExtendedState(MAXIMIZED_BOTH);
        
        jmAlterar.setVisible(false);
        
        new Funcoes().executeTimer(jtxtDataHora, "dd/MM/yyyy hh:mm:ss");
        
    }
    
    private static String[] argumento;


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jspFundo = new javax.swing.JScrollPane();
        jpBase = new javax.swing.JPanel();
        jtxtNovoConteudo = new javax.swing.JTextField();
        jtxtConteudo = new javax.swing.JTextField();
        jtxtDesc = new javax.swing.JTextField();
        jtxtUsuario = new javax.swing.JTextField();
        jtxtDataHora = new javax.swing.JTextField();
        jmbMenu = new javax.swing.JMenuBar();
        jmAlterar = new javax.swing.JMenu();
        jmMenu = new javax.swing.JMenu();
        jmLimpar = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Modificar Pessoa");
        setName("jfModificaPess"); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jpBase.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 102), 5, true));

        jtxtNovoConteudo.setEditable(false);
        jtxtNovoConteudo.setBackground(new java.awt.Color(255, 0, 102));
        jtxtNovoConteudo.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jtxtNovoConteudo.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 0, 153), 5, true), "Novo conteúdo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 48), new java.awt.Color(204, 204, 0))); // NOI18N
        jtxtNovoConteudo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtNovoConteudoMouseClicked(evt);
            }
        });

        jtxtConteudo.setEditable(false);
        jtxtConteudo.setBackground(new java.awt.Color(255, 0, 102));
        jtxtConteudo.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jtxtConteudo.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 0, 153), 5, true), "Conteúdo atual", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 48), new java.awt.Color(204, 204, 0))); // NOI18N

        jtxtDesc.setEditable(false);
        jtxtDesc.setBackground(new java.awt.Color(255, 0, 102));
        jtxtDesc.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jtxtDesc.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 0, 153), 5, true), "Descrição", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 48), new java.awt.Color(204, 204, 0))); // NOI18N
        jtxtDesc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtDescMouseClicked(evt);
            }
        });

        jtxtUsuario.setEditable(false);
        jtxtUsuario.setBackground(new java.awt.Color(255, 0, 102));
        jtxtUsuario.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jtxtUsuario.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 153), 5), "Usuário", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 48), new java.awt.Color(204, 204, 0))); // NOI18N

        jtxtDataHora.setEditable(false);
        jtxtDataHora.setBackground(new java.awt.Color(255, 0, 102));
        jtxtDataHora.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jtxtDataHora.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 0, 153), 5, true), "Data e Hora", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 48), new java.awt.Color(204, 204, 0))); // NOI18N

        javax.swing.GroupLayout jpBaseLayout = new javax.swing.GroupLayout(jpBase);
        jpBase.setLayout(jpBaseLayout);
        jpBaseLayout.setHorizontalGroup(
            jpBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpBaseLayout.createSequentialGroup()
                .addGroup(jpBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpBaseLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jpBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtNovoConteudo, javax.swing.GroupLayout.PREFERRED_SIZE, 487, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jpBaseLayout.createSequentialGroup()
                                .addComponent(jtxtDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(jtxtConteudo, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jpBaseLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jtxtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 1133, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpBaseLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jtxtDataHora, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(110, Short.MAX_VALUE))
        );
        jpBaseLayout.setVerticalGroup(
            jpBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpBaseLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtConteudo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(jtxtNovoConteudo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(180, 180, 180)
                .addComponent(jtxtDataHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jtxtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(422, Short.MAX_VALUE))
        );

        jspFundo.setViewportView(jpBase);

        jmbMenu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 153), 7));
        jmbMenu.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N

        jmAlterar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 255, 0), 5, true));
        jmAlterar.setText("Alterar");
        jmAlterar.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jmAlterar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmAlterarMouseClicked(evt);
            }
        });
        jmbMenu.add(jmAlterar);

        jmMenu.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 255, 0), 5, true));
        jmMenu.setText("Menu Principal");
        jmMenu.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jmMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmMenuMouseClicked(evt);
            }
        });
        jmbMenu.add(jmMenu);

        jmLimpar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 255, 0), 5, true));
        jmLimpar.setText("Limpar");
        jmLimpar.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jmLimpar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmLimparMouseClicked(evt);
            }
        });
        jmbMenu.add(jmLimpar);

        setJMenuBar(jmbMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jspFundo, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jspFundo, javax.swing.GroupLayout.DEFAULT_SIZE, 718, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmMenuMouseClicked
        // Vai para o menu principal e fecha o atual.

        MenuPrincipal.main(argumento, jtxtUsuario.getText());

        AlteraPessoa.this.dispose(); // Fecha o frame.

    }//GEN-LAST:event_jmMenuMouseClicked

    private void jmLimparMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmLimparMouseClicked
        //Limpa o formulário.

        jtxtDesc.setText("");

        jtxtConteudo.setText("");

        jtxtNovoConteudo.setText("");

        alterado = "";
        
        jmAlterar.setVisible(false);
        
        trava = false;

    }//GEN-LAST:event_jmLimparMouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        //Pega o valor do dado alterado.
        
       if(jtxtDesc.getText().compareTo("Código") == 0) 
                
                alterado = "codigo";
                
            
        
        if(jtxtDesc.getText().compareTo("Nome Completo") == 0) 
                
                alterado = "nomeCompleto";
        
        // Vai decidir se pode ou não liberar o botão de alterar.
        
        if (
            
                
                
                        (jtxtDesc.getText().isEmpty() == false) &&
                
                        (jtxtConteudo.getText().isEmpty() == false) &&
                
                        (jtxtNovoConteudo.getText().isEmpty() == false) && (trava == false)
                
              
                
                
            ){
                
                    jmAlterar.setVisible(true);
                    
                    trava = true;
                    
        }
            
      
        
    }//GEN-LAST:event_formWindowActivated

    private void jtxtDescMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtDescMouseClicked
        //Seleciona o dado a ser alterado.
        
        if(jtxtDesc.getText().isEmpty() == true)
            
            ListagemPessoa.main(argumento, jtxtConteudo, jtxtDesc,"Alteração de dados", false, jtxtUsuario.getText(), "Selecione o registro a ser modificado.");
        
        
    }//GEN-LAST:event_jtxtDescMouseClicked

    private void jmAlterarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmAlterarMouseClicked
        // Trata da alteração.
        
            jmAlterar.setVisible(false);
        
            String d[][] = new String[2][2];
            
            d[0][0] = "String";
        
            d[0][1] = jtxtNovoConteudo.getText();
        
            d[1][0] = d[0][0];
        
            d[1][1] = jtxtConteudo.getText();
          
            if(alterado == "codigo"){
                
                String consulta[][] = new String[1][2];
            
                consulta[0][0] = d[0][0];
            
                consulta[0][1] = d[1][1];
                
                if(new Funcoes().retornar("SELECT login from login where codigoPessoa = ?", "login", consulta) != null)
                
                        new Funcoes().executa("update login set codigoPessoa =  ? where codigoPessoa = ? " , d, "Alteração na tabela de login realizada com sucesso.");
            
                if(new Funcoes().retornar("SELECT valor from meta where codigoPessoa = ?", "valor", consulta) != null)
                
                        new Funcoes().executa("update meta set codigoPessoa =  ? where codigoPessoa = ? " , d, "Alteração na tabela de metas realizada com sucesso. ");
            
                if(new Funcoes().retornar("SELECT valor from divida where codigoPessoa = ?", "valor", consulta) != null)
                
                        new Funcoes().executa("update divida set codigoPessoa =  ? where codigoPessoa = ? " , d, "Alteração na tabela de metas realizada com sucesso. Use o botão modo default para limpar a tela.");
            
                if(new Funcoes().retornar("SELECT valor from gasto where codigoPessoa = ?", "valor", consulta) != null)
                
                        new Funcoes().executa("update gasto set codigoPessoa =  ? where codigoPessoa = ? " , d, "Alteração na tabela de gastos realizada com sucesso. ");
            
                if(new Funcoes().retornar("SELECT valor from entradaCapital where codigoPessoa = ?", "valor", consulta) != null)
                
                        new Funcoes().executa("update entradaCapital set codigoPessoa =  ? where codigoPessoa = ? " , d, "Alteração na tabela de entrada de capital realizada com sucesso.");
            
                
            }
            
            new Funcoes().executa("update pessoa set " + alterado + " = ? where " +  alterado + " = ? " , d, "Alteração na tabela de pessoas realizada com sucesso. ");

            
        
        
    }//GEN-LAST:event_jmAlterarMouseClicked

    private void jtxtNovoConteudoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtNovoConteudoMouseClicked
        // Escolhe um dado caminho dependendo do valor em alterado.
        
        if(alterado == "codigo") 
          
            EntradaValores.main(argumento, jtxtNovoConteudo, true, jtxtUsuario.getText(), "Insira o " + jtxtDesc.getText() + ".");
        
        else
            
            EntradaValores.main(argumento, jtxtNovoConteudo, false, jtxtUsuario.getText(), "Insira o " + jtxtDesc.getText() + ".");
        
    }//GEN-LAST:event_jtxtNovoConteudoMouseClicked

    /**
     * @param args the command line arguments
     */
   
    public static void main(String args[], String user) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlteraPessoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlteraPessoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlteraPessoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlteraPessoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new AlteraPessoa().setVisible(true);
                
                jtxtUsuario.setText(user);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jmAlterar;
    private javax.swing.JMenu jmLimpar;
    private javax.swing.JMenu jmMenu;
    private javax.swing.JMenuBar jmbMenu;
    private javax.swing.JPanel jpBase;
    private javax.swing.JScrollPane jspFundo;
    private javax.swing.JTextField jtxtConteudo;
    private javax.swing.JTextField jtxtDataHora;
    private javax.swing.JTextField jtxtDesc;
    private javax.swing.JTextField jtxtNovoConteudo;
    private static javax.swing.JTextField jtxtUsuario;
    // End of variables declaration//GEN-END:variables
}
