/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package doug;

/**
 *
 * @author Douglas
 */




public class AlteraCatalogo extends javax.swing.JFrame {

    /**
     * Creates new form AlterandoRegistroCatalogado
     */

    public AlteraCatalogo() {
        initComponents();
      
        this.setExtendedState(MAXIMIZED_BOTH);
        
        jmAlterar.setVisible(false);
        
        new Funcoes().executeTimer(jtxtDataHora, "dd/MM/yyyy hh:mm:ss");
        
    }
    
    private static String[] argumento;
    
    private  boolean trava;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jspFundo = new javax.swing.JScrollPane();
        jpBase = new javax.swing.JPanel();
        jtxtNovoConteudo = new javax.swing.JTextField();
        jtxtConteudo = new javax.swing.JTextField();
        jtxtDesc = new javax.swing.JTextField();
        jtxtUsuario = new javax.swing.JTextField();
        jtxtDataHora = new javax.swing.JTextField();
        jmbMenu = new javax.swing.JMenuBar();
        jmAlterar = new javax.swing.JMenu();
        jmMenu = new javax.swing.JMenu();
        jmLimpa = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Altera dados de registros catalogados");
        setBackground(new java.awt.Color(204, 204, 0));
        setForeground(new java.awt.Color(255, 204, 204));
        setName("jfAlteraCat"); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jpBase.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 255), 5, true));

        jtxtNovoConteudo.setEditable(false);
        jtxtNovoConteudo.setBackground(new java.awt.Color(51, 51, 255));
        jtxtNovoConteudo.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jtxtNovoConteudo.setForeground(new java.awt.Color(51, 0, 153));
        jtxtNovoConteudo.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 255, 204), 5, true), "Novo Conteúdo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 48), new java.awt.Color(51, 51, 51))); // NOI18N
        jtxtNovoConteudo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtNovoConteudoMouseClicked(evt);
            }
        });

        jtxtConteudo.setEditable(false);
        jtxtConteudo.setBackground(new java.awt.Color(51, 51, 255));
        jtxtConteudo.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jtxtConteudo.setForeground(new java.awt.Color(51, 0, 153));
        jtxtConteudo.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 255, 204), 5, true), "Conteúdo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 48), new java.awt.Color(51, 51, 51))); // NOI18N

        jtxtDesc.setEditable(false);
        jtxtDesc.setBackground(new java.awt.Color(51, 51, 255));
        jtxtDesc.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jtxtDesc.setForeground(new java.awt.Color(51, 0, 153));
        jtxtDesc.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 255, 204), 5, true), "Descrição", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 48), new java.awt.Color(51, 51, 51))); // NOI18N
        jtxtDesc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtDescMouseClicked(evt);
            }
        });

        jtxtUsuario.setEditable(false);
        jtxtUsuario.setBackground(new java.awt.Color(51, 51, 255));
        jtxtUsuario.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jtxtUsuario.setForeground(new java.awt.Color(51, 0, 153));
        jtxtUsuario.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 255, 204), 5), "Usuário", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 48), new java.awt.Color(51, 51, 51))); // NOI18N

        jtxtDataHora.setEditable(false);
        jtxtDataHora.setBackground(new java.awt.Color(51, 51, 255));
        jtxtDataHora.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jtxtDataHora.setForeground(new java.awt.Color(51, 0, 153));
        jtxtDataHora.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 255, 204), 5, true), "Data e Hora", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 48), new java.awt.Color(51, 51, 51))); // NOI18N

        javax.swing.GroupLayout jpBaseLayout = new javax.swing.GroupLayout(jpBase);
        jpBase.setLayout(jpBaseLayout);
        jpBaseLayout.setHorizontalGroup(
            jpBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpBaseLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtxtDataHora, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpBaseLayout.createSequentialGroup()
                        .addComponent(jtxtDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jtxtConteudo, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jtxtNovoConteudo, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 1140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(101, Short.MAX_VALUE))
        );
        jpBaseLayout.setVerticalGroup(
            jpBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpBaseLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtConteudo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addComponent(jtxtNovoConteudo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(165, 165, 165)
                .addComponent(jtxtDataHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jtxtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(348, Short.MAX_VALUE))
        );

        jspFundo.setViewportView(jpBase);

        jmbMenu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 153), 10));
        jmbMenu.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N

        jmAlterar.setBackground(new java.awt.Color(0, 153, 153));
        jmAlterar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 0), 5, true));
        jmAlterar.setForeground(new java.awt.Color(0, 51, 51));
        jmAlterar.setText("Alterar");
        jmAlterar.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jmAlterar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmAlterarMouseClicked(evt);
            }
        });
        jmbMenu.add(jmAlterar);

        jmMenu.setBackground(new java.awt.Color(0, 153, 153));
        jmMenu.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 0), 5, true));
        jmMenu.setForeground(new java.awt.Color(0, 51, 51));
        jmMenu.setText("Menu Principal");
        jmMenu.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jmMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmMenuMouseClicked(evt);
            }
        });
        jmbMenu.add(jmMenu);

        jmLimpa.setBackground(new java.awt.Color(0, 153, 153));
        jmLimpa.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 0), 5, true));
        jmLimpa.setForeground(new java.awt.Color(0, 51, 51));
        jmLimpa.setText("Limpar");
        jmLimpa.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jmLimpa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmLimpaMouseClicked(evt);
            }
        });
        jmbMenu.add(jmLimpa);

        setJMenuBar(jmbMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jspFundo, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jspFundo, javax.swing.GroupLayout.DEFAULT_SIZE, 712, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmMenuMouseClicked
        // Vai para o menu principal e fecha o atual.
        
        MenuPrincipal.main(argumento, jtxtUsuario.getText());

        AlteraCatalogo.this.dispose(); // Fecha o frame.
        
    }//GEN-LAST:event_jmMenuMouseClicked

    private void jmLimpaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmLimpaMouseClicked
         //Limpa o formulário.

        jtxtDesc.setText("");
        
        jtxtConteudo.setText("");
        
        jtxtNovoConteudo.setText("");
        
        jmAlterar.setVisible(false);
        
        trava = false;
     
        
    }//GEN-LAST:event_jmLimpaMouseClicked

    private void jtxtDescMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtDescMouseClicked
        // Seleciona o campo a ser alterado.
        
        if(jtxtDesc.getText().isEmpty() == true){
            
            ListagemCatalogo.main(argumento, jtxtConteudo, jtxtDesc, null,"Alteração de dados", false, jtxtUsuario.getText(), "Selecione o registro a ser modificado.");
            
        }
        
    }//GEN-LAST:event_jtxtDescMouseClicked

    private void jtxtNovoConteudoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtNovoConteudoMouseClicked
        // Dependendo do que for alterar, irá para uma tela de entrada de dados diferente.
        
        if ( (jtxtDesc.getText().isEmpty() == false) && (jtxtNovoConteudo.getText().isEmpty() == true)) {
            
            if ( (jtxtDesc.getText().compareTo("Código") == 0 ) || (jtxtDesc.getText().compareTo("Valor unitário em reais") == 0 ) )
                
                EntradaValores.main(argumento, jtxtNovoConteudo, true, jtxtUsuario.getText(), "Insira o " + jtxtDesc.getText() + ".");
        
            
            if(jtxtDesc.getText().compareTo("Descrição") == 0 ) 
                
                 EntradaValores.main(argumento, jtxtNovoConteudo, false, jtxtUsuario.getText(), "Insira a " + jtxtDesc.getText()+ ".");
            
            if((jtxtDesc.getText().compareTo("Data em que viu o preço") == 0 ))
                
                Data.main(argumento, jtxtNovoConteudo, 1000, "Selecione nova data.", jtxtUsuario.getText());
        
            
        }
        
    }//GEN-LAST:event_jtxtNovoConteudoMouseClicked

    private void jmAlterarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmAlterarMouseClicked
        // Trata da alteração.
        
        jmAlterar.setVisible(false);
        
        String alterado = "";
        
        String c1[][] = new String[1][2];
        
        String d[][] = new String[2][2];
        
        d[0][1] = jtxtNovoConteudo.getText();
   
        d[1][1] = jtxtConteudo.getText();
        
        if(jtxtDesc.getText().compareTo("Descrição") == 0) {
                
                alterado = "descricao";
                
                d[0][0] = "String";
                
                d[1][0] = d[0][0];
                
              
                
        }
              
            
        if(jtxtDesc.getText().compareTo("Valor unitário em reais") == 0) {
                
                alterado = "valorUnitario";
                
                d[0][0] = "Double";
                
                d[1][0] = d[0][0];
                
                
                
        }
            
        if(jtxtDesc.getText().compareTo("Código") == 0) {
                
                alterado = "codigo";
                
                d[0][0] = "Double";
                
                d[1][0] = d[0][0];
                
                c1[0][0] = d[0][0];
                
                c1[0][1] = jtxtConteudo.getText();
                
                if(new Funcoes().retornar("select quantidade from item where codigoCatalogo = ?", "quantidade", c1) != null)
 
                    new Funcoes().executa("update item set codigoCatalogo =  ? where codigoCatalogo = ? " , d, "Alteração na tabela de ítens realizada com sucesso.");
                
        }
        
         if(jtxtDesc.getText().compareTo("Fornecedor do produto/serviço" ) == 0) {
                
                alterado = "fornecedor";
                
                d[0][0] = "String";
                
                d[1][0] = d[0][0];
                
              
                
        }
         
        
     
        new Funcoes().executa("update catalogo set " + alterado + " = ? where " +  alterado + " =  ? " , d, "Alteração na tabela de catálogo realizada com sucesso.");
       
            
    }//GEN-LAST:event_jmAlterarMouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // Vai decidir se pode ou não liberar o botão de alterar.
        
        if (
            
                
                
                        (jtxtDesc.getText().isEmpty() == false) &&
                
                        (jtxtConteudo.getText().isEmpty() == false) &&
                
                        (jtxtNovoConteudo.getText().isEmpty() == false) && (trava == false)
                
              
                
                
            ) {
            
                trava = true;
        
                jmAlterar.setVisible(true);
                
        }
            
            
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[], String user) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlteraCatalogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlteraCatalogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlteraCatalogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlteraCatalogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AlteraCatalogo().setVisible(true);
                
                jtxtUsuario.setText(user);
                
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jmAlterar;
    private javax.swing.JMenu jmLimpa;
    private javax.swing.JMenu jmMenu;
    private javax.swing.JMenuBar jmbMenu;
    private javax.swing.JPanel jpBase;
    private javax.swing.JScrollPane jspFundo;
    private javax.swing.JTextField jtxtConteudo;
    private javax.swing.JTextField jtxtDataHora;
    private javax.swing.JTextField jtxtDesc;
    private javax.swing.JTextField jtxtNovoConteudo;
    private static javax.swing.JTextField jtxtUsuario;
    // End of variables declaration//GEN-END:variables
}
