/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package doug;

import javax.swing.JOptionPane;

/**
 *
 * @author Douglas
 */





public class AlteraGasto extends javax.swing.JFrame {

    /**
     * Creates new form Alterardadoscompra
     */

    public AlteraGasto() {
        initComponents();
        
        this.setExtendedState(MAXIMIZED_BOTH);
        
        jmAltera.setVisible(false);
        
        jtxtDesconto.setVisible(false);
        
        jtxtValor.setVisible(false);
        
        new Funcoes().executeTimer(jtxtDataHora, "dd/MM/yyyy hh:mm:ss");
        
    }
    
    private static String[] argumento;
    
    private boolean trava;
    
 
    
   
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jspFundo = new javax.swing.JScrollPane();
        jpBase = new javax.swing.JPanel();
        jtxtNovoConteudo = new javax.swing.JTextField();
        jtxtConteudo = new javax.swing.JTextField();
        jtxtDesc = new javax.swing.JTextField();
        jtxtUsuario = new javax.swing.JTextField();
        jtxtValor = new javax.swing.JTextField();
        jtxtDesconto = new javax.swing.JTextField();
        jtxtDataHora = new javax.swing.JTextField();
        jmbMenu = new javax.swing.JMenuBar();
        jmAltera = new javax.swing.JMenu();
        jmMenu = new javax.swing.JMenu();
        jmLimpar = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Alterar dados de gastos");
        setBackground(new java.awt.Color(204, 255, 204));
        setForeground(java.awt.Color.magenta);
        setName("jfAlteraDadosGasto"); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jpBase.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 5, true));

        jtxtNovoConteudo.setEditable(false);
        jtxtNovoConteudo.setBackground(new java.awt.Color(51, 255, 51));
        jtxtNovoConteudo.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jtxtNovoConteudo.setForeground(new java.awt.Color(102, 102, 102));
        jtxtNovoConteudo.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 5, true), "Novo Conteúdo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 48), new java.awt.Color(153, 153, 153))); // NOI18N
        jtxtNovoConteudo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtNovoConteudoMouseClicked(evt);
            }
        });

        jtxtConteudo.setEditable(false);
        jtxtConteudo.setBackground(new java.awt.Color(51, 255, 51));
        jtxtConteudo.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jtxtConteudo.setForeground(new java.awt.Color(102, 102, 102));
        jtxtConteudo.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 0, 102), 5, true), "Conteúdo atual", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 48), new java.awt.Color(153, 153, 153))); // NOI18N

        jtxtDesc.setEditable(false);
        jtxtDesc.setBackground(new java.awt.Color(51, 255, 51));
        jtxtDesc.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jtxtDesc.setForeground(new java.awt.Color(102, 102, 102));
        jtxtDesc.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 102), 5), "Descrição ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 48), new java.awt.Color(153, 153, 153))); // NOI18N
        jtxtDesc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtDescMouseClicked(evt);
            }
        });

        jtxtUsuario.setEditable(false);
        jtxtUsuario.setBackground(new java.awt.Color(51, 255, 51));
        jtxtUsuario.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jtxtUsuario.setForeground(new java.awt.Color(102, 102, 102));
        jtxtUsuario.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 102), 5), "Usuário", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 48), new java.awt.Color(153, 153, 153))); // NOI18N

        jtxtValor.setEditable(false);
        jtxtValor.setBackground(new java.awt.Color(51, 255, 51));
        jtxtValor.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jtxtValor.setForeground(new java.awt.Color(102, 102, 102));
        jtxtValor.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 5, true), "Valor", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 48), new java.awt.Color(153, 153, 153))); // NOI18N

        jtxtDesconto.setEditable(false);
        jtxtDesconto.setBackground(new java.awt.Color(51, 255, 51));
        jtxtDesconto.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jtxtDesconto.setForeground(new java.awt.Color(102, 102, 102));
        jtxtDesconto.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 5, true), "Desconto", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 48), new java.awt.Color(153, 153, 153))); // NOI18N

        jtxtDataHora.setEditable(false);
        jtxtDataHora.setBackground(new java.awt.Color(51, 255, 51));
        jtxtDataHora.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jtxtDataHora.setForeground(new java.awt.Color(102, 102, 102));
        jtxtDataHora.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 0, 102), 5, true), "Data e Hora", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 48), new java.awt.Color(153, 153, 153))); // NOI18N

        javax.swing.GroupLayout jpBaseLayout = new javax.swing.GroupLayout(jpBase);
        jpBase.setLayout(jpBaseLayout);
        jpBaseLayout.setHorizontalGroup(
            jpBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpBaseLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtxtNovoConteudo, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpBaseLayout.createSequentialGroup()
                        .addComponent(jtxtDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(jtxtConteudo, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jtxtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 1154, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtDataHora, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(81, Short.MAX_VALUE))
        );
        jpBaseLayout.setVerticalGroup(
            jpBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpBaseLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jtxtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(jpBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtConteudo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(jtxtNovoConteudo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84)
                .addComponent(jtxtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addComponent(jtxtDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(148, 148, 148)
                .addComponent(jtxtDataHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jspFundo.setViewportView(jpBase);

        jmbMenu.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 102), 10, true));
        jmbMenu.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N

        jmAltera.setBackground(new java.awt.Color(0, 51, 204));
        jmAltera.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 0), 5, true));
        jmAltera.setForeground(new java.awt.Color(0, 0, 204));
        jmAltera.setText("Alterar");
        jmAltera.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jmAltera.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmAlteraMouseClicked(evt);
            }
        });
        jmbMenu.add(jmAltera);

        jmMenu.setBackground(new java.awt.Color(0, 51, 204));
        jmMenu.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 0), 5, true));
        jmMenu.setForeground(new java.awt.Color(0, 0, 204));
        jmMenu.setText("Menu Principal");
        jmMenu.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jmMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmMenuMouseClicked(evt);
            }
        });
        jmbMenu.add(jmMenu);

        jmLimpar.setBackground(new java.awt.Color(0, 51, 204));
        jmLimpar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 0), 5, true));
        jmLimpar.setForeground(new java.awt.Color(0, 0, 204));
        jmLimpar.setText("Limpar");
        jmLimpar.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jmLimpar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmLimparMouseClicked(evt);
            }
        });
        jmbMenu.add(jmLimpar);

        setJMenuBar(jmbMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jspFundo, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jspFundo, javax.swing.GroupLayout.DEFAULT_SIZE, 712, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmMenuMouseClicked
        // Vai para o menu principal e fecha o atual.

        MenuPrincipal.main(argumento, jtxtUsuario.getText());

        AlteraGasto.this.dispose(); // Fecha o frame.

    }//GEN-LAST:event_jmMenuMouseClicked

    private void jmLimparMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmLimparMouseClicked
        //Limpar o formulário.


        jtxtDesc.setText("");

        jtxtConteudo.setText("");

        jtxtNovoConteudo.setText("");
        
        jtxtValor.setText("");
        
        jtxtDesconto.setText("");

        jmAltera.setVisible(false);
        
        trava = false;
        
    }//GEN-LAST:event_jmLimparMouseClicked

    private void jtxtDescMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtDescMouseClicked
        // Seleciona o dado a ser alterado.
        
        if(jtxtDesc.getText().length() == 0)
            
            ListagemGasto.main(argumento, jtxtConteudo, jtxtDesc,"Alteração de dados", false, jtxtUsuario.getText(), "Selecione o registro a ser alterado.", jtxtDesconto, jtxtValor);
 
        
    }//GEN-LAST:event_jtxtDescMouseClicked

    private void jtxtNovoConteudoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtNovoConteudoMouseClicked
        // Dependendo do que for alterar, irá para uma tela de entrada de dados diferente.
        
        if ( (jtxtDesc.getText().isEmpty() == false) && (jtxtNovoConteudo.getText().isEmpty() == true)) {
            
            if ( (jtxtDesc.getText().compareTo("Código do gasto") == 0 ) || (jtxtDesc.getText().compareTo("Valor em reais") == 0 ) || (jtxtDesc.getText().compareTo("Desconto em reais") == 0 ) )
                
               EntradaValores.main(argumento, jtxtNovoConteudo, true, jtxtUsuario.getText(), "Insira o " + jtxtDesc.getText() + ".");
           
            else {
                
                if ( jtxtDesc.getText().compareTo("Descrição") == 0 )
                
                    EntradaValores.main(argumento, jtxtNovoConteudo, false, jtxtUsuario.getText(), "Insira a " + jtxtDesc.getText() + ".");
                
                else
                    
                    Data.main(argumento, jtxtNovoConteudo,10, "Insira a data do gasto.", jtxtUsuario.getText());
                
            }
                
               
            
        }
        
        
    }//GEN-LAST:event_jtxtNovoConteudoMouseClicked

    private void jmAlteraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmAlteraMouseClicked
        //Trata da alteração.
        
        
        
        jmAltera.setVisible(false);
        
        String alterado = "";
        
        String d[][] = new String[2][2];
        
        d[0][1] = jtxtNovoConteudo.getText().trim();
   
        d[1][1] = jtxtConteudo.getText().trim();
     
        if(jtxtDesc.getText().compareTo("Descrição") == 0) {
                
                alterado = "descricao";
                
                d[0][0] = "String";
                
                d[1][0] = d[0][0];
                
        }
              
            
        if(jtxtDesc.getText().compareTo("Data") == 0) {
                
                alterado = "data";
                
                d[0][0] = "Date";
                
                d[1][0] = d[0][0];
                
                
                
        }
            
        if(jtxtDesc.getText().compareTo("Desconto em reais") == 0) {
                
                alterado = "desconto";
                
                d[0][0] = "Double";
                
                d[1][0] = d[0][0];
                
        }
            
        if(jtxtDesc.getText().compareTo("Código do gasto") == 0) {
                
                alterado = "codigo";
                
                d[0][0] = "Double";
                
                d[1][0] = d[0][0];
                
                String c1[][] = new String[1][2];
                
                c1[0][0] = d[0][0];
                
                c1[0][1] = jtxtConteudo.getText();
                
                 if(new Funcoes().retornar("select total from item where codigoGasto = ?", "total", c1) != null)
 
               
                    new Funcoes().executa("update item set codigoGasto" + " = ? where " +  alterado + " =  ? " , d, "Alteração na tabela de gastos realizada com sucesso.");

                
             
        }
            
                
        if(jtxtDesc.getText().compareTo("Valor em reais") == 0) {
                
                alterado = "valor";
                
                d[0][0] = "Double";
                
                d[1][0] = d[0][0];
                
        }
        
        
       
                    
        new Funcoes().executa("update gasto set " + alterado + " = ? where " +  alterado + " =  ? " , d, "Alteração na tabela de gastos realizada com sucesso.");

           
           
                
                
    }//GEN-LAST:event_jmAlteraMouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        
        // Tratar a restrição do valor e do desconto
        
         if (   (jtxtNovoConteudo.getText().isEmpty() == false)   && (trava == false) &&
                 
                ( ( (jtxtDesc.getText().compareTo("Valor em reais") == 0) && 
                
                           ((Double.parseDouble(jtxtNovoConteudo.getText())) < ( Double.parseDouble(jtxtDesconto.getText()))) )  ||
                            
                        ( (jtxtDesc.getText().compareTo("Desconto em reais") == 0) && 
                
                           ((Double.parseDouble(jtxtNovoConteudo.getText())) > ( Double.parseDouble(jtxtValor.getText()))) )  ) ) {
            
           
            trava = true;
            
            JOptionPane.showMessageDialog(null,"Lembre - se que o desconto no gasto é menor do que o valor do gasto." , "System Message", JOptionPane.INFORMATION_MESSAGE);
                
            
        }

        // Vai decidir se pode ou não liberar o botão de alterar.
        
        if (
            
                
                
                        (jtxtDesc.getText().isEmpty() == false) &&
                
                        (jtxtConteudo.getText().isEmpty() == false) &&
                
                        (jtxtNovoConteudo.getText().isEmpty() == false) && (trava == false) 
                
                       
                
                
            ) {
            
                trava = true;
        
                jmAltera.setVisible(true);
                 
        }
        
        
         
       
        
       
            
            
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[], String user) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlteraGasto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlteraGasto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlteraGasto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlteraGasto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AlteraGasto().setVisible(true);
                
                jtxtUsuario.setText(user);
                
               
                
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jmAltera;
    private javax.swing.JMenu jmLimpar;
    private javax.swing.JMenu jmMenu;
    private javax.swing.JMenuBar jmbMenu;
    private javax.swing.JPanel jpBase;
    private javax.swing.JScrollPane jspFundo;
    private javax.swing.JTextField jtxtConteudo;
    private javax.swing.JTextField jtxtDataHora;
    private javax.swing.JTextField jtxtDesc;
    private javax.swing.JTextField jtxtDesconto;
    private javax.swing.JTextField jtxtNovoConteudo;
    private static javax.swing.JTextField jtxtUsuario;
    private javax.swing.JTextField jtxtValor;
    // End of variables declaration//GEN-END:variables
}
