/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package doug;


import java.awt.Color;

import javax.swing.JOptionPane;


/**
 *
 * @author Douglas
 */



public class AnalisaGastos extends javax.swing.JFrame {

    /**
     * Creates new form AnáliseGasto
     */

    
    private String[] argumento;
    
    
    private boolean trava = false;
   
    public AnalisaGastos() {
        initComponents();
     
        this.setExtendedState(MAXIMIZED_BOTH);
        
        jmAnalisar.setVisible(false);
        
        new Funcoes().executeTimer(jtxtDataHora, "dd/MM/yyyy hh:mm:ss");
        
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jspFundo = new javax.swing.JScrollPane();
        jpBase = new javax.swing.JPanel();
        jtxtUsuario = new javax.swing.JTextField();
        jpSaida = new javax.swing.JPanel();
        jtxtSituacao = new javax.swing.JTextField();
        jtxtResult = new javax.swing.JTextField();
        txtInfoMeta = new javax.swing.JTextField();
        jtxtResultPess = new javax.swing.JTextField();
        jpEntrada = new javax.swing.JPanel();
        jtxtMes = new javax.swing.JTextField();
        jtxtAno = new javax.swing.JTextField();
        jtxtCodigoPessoa = new javax.swing.JTextField();
        jtxtDataHora = new javax.swing.JTextField();
        jmbMenu = new javax.swing.JMenuBar();
        jmAnalisar = new javax.swing.JMenu();
        jmMenu = new javax.swing.JMenu();
        jmLimpar = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Análise de gastos");
        setBackground(new java.awt.Color(0, 102, 204));
        setForeground(new java.awt.Color(255, 255, 0));
        setName("jfAnalise"); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jpBase.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));

        jtxtUsuario.setEditable(false);
        jtxtUsuario.setBackground(java.awt.Color.darkGray);
        jtxtUsuario.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jtxtUsuario.setForeground(java.awt.Color.green);
        jtxtUsuario.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 153), 5, true), "Usuário", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 48), new java.awt.Color(209, 91, 71))); // NOI18N

        jpSaida.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 153), 5, true), "Saída de dados", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 48), new java.awt.Color(209, 91, 71))); // NOI18N
        jpSaida.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N

        jtxtSituacao.setEditable(false);
        jtxtSituacao.setBackground(java.awt.Color.darkGray);
        jtxtSituacao.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jtxtSituacao.setForeground(java.awt.Color.green);
        jtxtSituacao.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 153), 5, true), "Situação", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 48), new java.awt.Color(209, 91, 71))); // NOI18N

        jtxtResult.setEditable(false);
        jtxtResult.setBackground(java.awt.Color.darkGray);
        jtxtResult.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jtxtResult.setForeground(java.awt.Color.green);
        jtxtResult.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 153), 5, true), "Somatório dos gastos de todos os usuários", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 48), new java.awt.Color(209, 91, 71))); // NOI18N

        txtInfoMeta.setEditable(false);
        txtInfoMeta.setBackground(java.awt.Color.darkGray);
        txtInfoMeta.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        txtInfoMeta.setForeground(java.awt.Color.green);
        txtInfoMeta.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 153), 5, true), "Atingiu a meta ?", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 48), new java.awt.Color(209, 91, 71))); // NOI18N

        jtxtResultPess.setEditable(false);
        jtxtResultPess.setBackground(java.awt.Color.darkGray);
        jtxtResultPess.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jtxtResultPess.setForeground(java.awt.Color.green);
        jtxtResultPess.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 153), 5, true), "Somatório dos gastos do usuário logado", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 48), new java.awt.Color(209, 91, 71))); // NOI18N

        javax.swing.GroupLayout jpSaidaLayout = new javax.swing.GroupLayout(jpSaida);
        jpSaida.setLayout(jpSaidaLayout);
        jpSaidaLayout.setHorizontalGroup(
            jpSaidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpSaidaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpSaidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtxtResult, javax.swing.GroupLayout.PREFERRED_SIZE, 1127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtResultPess, javax.swing.GroupLayout.PREFERRED_SIZE, 1030, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jpSaidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jpSaidaLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jtxtSituacao, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(53, 53, 53)
                    .addComponent(txtInfoMeta, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(159, Short.MAX_VALUE)))
        );
        jpSaidaLayout.setVerticalGroup(
            jpSaidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpSaidaLayout.createSequentialGroup()
                .addContainerGap(168, Short.MAX_VALUE)
                .addComponent(jtxtResultPess, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jtxtResult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jpSaidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jpSaidaLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jpSaidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtxtSituacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtInfoMeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(335, Short.MAX_VALUE)))
        );

        jpEntrada.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 153), 5, true), "Entrada de dados", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 48), new java.awt.Color(209, 91, 71))); // NOI18N
        jpEntrada.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N

        jtxtMes.setEditable(false);
        jtxtMes.setBackground(java.awt.Color.darkGray);
        jtxtMes.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jtxtMes.setForeground(java.awt.Color.green);
        jtxtMes.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 153), 5, true), "Mês", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 48), new java.awt.Color(209, 91, 71))); // NOI18N
        jtxtMes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtMesMouseClicked(evt);
            }
        });

        jtxtAno.setEditable(false);
        jtxtAno.setBackground(java.awt.Color.darkGray);
        jtxtAno.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jtxtAno.setForeground(java.awt.Color.green);
        jtxtAno.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 153), 5, true), "Ano", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 48), new java.awt.Color(209, 91, 71))); // NOI18N
        jtxtAno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtAnoMouseClicked(evt);
            }
        });

        jtxtCodigoPessoa.setEditable(false);
        jtxtCodigoPessoa.setBackground(java.awt.Color.darkGray);
        jtxtCodigoPessoa.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jtxtCodigoPessoa.setForeground(java.awt.Color.green);
        jtxtCodigoPessoa.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 153), 5, true), "Código da pessoa", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 48), new java.awt.Color(209, 91, 71))); // NOI18N
        jtxtCodigoPessoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtCodigoPessoaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jpEntradaLayout = new javax.swing.GroupLayout(jpEntrada);
        jpEntrada.setLayout(jpEntradaLayout);
        jpEntradaLayout.setHorizontalGroup(
            jpEntradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpEntradaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jtxtMes, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jtxtAno, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jtxtCodigoPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpEntradaLayout.setVerticalGroup(
            jpEntradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpEntradaLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(jpEntradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtCodigoPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(81, Short.MAX_VALUE))
        );

        jtxtDataHora.setEditable(false);
        jtxtDataHora.setBackground(java.awt.Color.darkGray);
        jtxtDataHora.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jtxtDataHora.setForeground(java.awt.Color.green);
        jtxtDataHora.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 153), 5, true), "Data e Hora", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 48), new java.awt.Color(209, 91, 71))); // NOI18N

        javax.swing.GroupLayout jpBaseLayout = new javax.swing.GroupLayout(jpBase);
        jpBase.setLayout(jpBaseLayout);
        jpBaseLayout.setHorizontalGroup(
            jpBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpBaseLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpSaida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpEntrada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jpBaseLayout.createSequentialGroup()
                        .addComponent(jtxtDataHora, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpBaseLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jtxtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 1154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jpBaseLayout.setVerticalGroup(
            jpBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpBaseLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jpSaida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtxtDataHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtxtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jspFundo.setViewportView(jpBase);

        jmbMenu.setBackground(new java.awt.Color(204, 255, 51));
        jmbMenu.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 10, true));
        jmbMenu.setForeground(new java.awt.Color(204, 51, 0));

        jmAnalisar.setBackground(new java.awt.Color(153, 0, 153));
        jmAnalisar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 102), 5, true));
        jmAnalisar.setForeground(new java.awt.Color(102, 0, 102));
        jmAnalisar.setText("Analisar");
        jmAnalisar.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jmAnalisar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmAnalisarMouseClicked(evt);
            }
        });
        jmbMenu.add(jmAnalisar);

        jmMenu.setBackground(new java.awt.Color(153, 0, 153));
        jmMenu.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 102), 5, true));
        jmMenu.setForeground(new java.awt.Color(102, 0, 102));
        jmMenu.setText("Menu Principal");
        jmMenu.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jmMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmMenuMouseClicked(evt);
            }
        });
        jmbMenu.add(jmMenu);

        jmLimpar.setBackground(new java.awt.Color(153, 0, 153));
        jmLimpar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 102), 5, true));
        jmLimpar.setForeground(new java.awt.Color(102, 0, 102));
        jmLimpar.setText("Limpar");
        jmLimpar.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jmLimpar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmLimparMouseClicked(evt);
            }
        });
        jmbMenu.add(jmLimpar);

        setJMenuBar(jmbMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jspFundo, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jspFundo, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmLimparMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmLimparMouseClicked
        // Limpa o formulário.
        
        jtxtMes.setText("");
        
        jtxtAno.setText("");
        
        jtxtSituacao.setText("");
        
        jtxtCodigoPessoa.setText("");
        
        txtInfoMeta.setText("");
       
        jtxtSituacao.setBackground(Color.DARK_GRAY);
        
        txtInfoMeta.setBackground(Color.DARK_GRAY);
       
        trava = false;
        
        jmAnalisar.setVisible(false);
        
        jtxtResult.setText("");
        
        jtxtResultPess.setText("");
        
    }//GEN-LAST:event_jmLimparMouseClicked

    private void jtxtMesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtMesMouseClicked
         //Vai para a tela de calendário.
        
        if(jtxtMes.getText().isEmpty() == true)
            
           Data.main(argumento, jtxtMes, 1 , "Insira o mês para análise.", jtxtUsuario.getText()); 
        
    }//GEN-LAST:event_jtxtMesMouseClicked

    private void jtxtAnoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtAnoMouseClicked
        //Vai para a tela de calendário.
        
        if(jtxtAno.getText().isEmpty() == true)
            
           Data.main(argumento, jtxtAno, 2, "Insira o ano referente ao mês analisado.", jtxtUsuario.getText());
        
    }//GEN-LAST:event_jtxtAnoMouseClicked

    private void jmAnalisarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmAnalisarMouseClicked
        // Faz a análise e mostra os resultados na tela.
        
        jmAnalisar.setVisible(false);
        
        double totPess = 0;
        
        double meta = 0;
        
        double renda = 0;
        
        double tot = 0;
      
        // Verifica se da para fazer a soma dos gastos de uma pessoa num dado mês dum ano e armazena na variável total.
        
        if( (new Funcoes().retornar("SELECT SUM(g.valor)"
                                + " FROM gasto as g"
                                + " WHERE codigoPessoa =  " + jtxtCodigoPessoa.getText() + 
                                        " AND ( MONTH( g.data ) =  " + jtxtMes.getText() + " AND YEAR( g.data) = " + jtxtAno.getText() + " ) " 
                        , "SUM(g.valor)", null) != null)  &&
                
            (new Funcoes().retornar("SELECT SUM(g.valor)"
                                + " FROM gasto as g"
                                + " WHERE (( MONTH( g.data ) =  " + jtxtMes.getText() + ") AND ( YEAR( g.data) = " + jtxtAno.getText() + " )) " 
                        , "SUM(g.valor)", null) != null) )
                
        
        {
       
        
                totPess = new Funcoes().round( (Double)new Funcoes().retornar("SELECT SUM(g.valor)"
                                + " FROM gasto as g"
                                + " WHERE codigoPessoa =  " + jtxtCodigoPessoa.getText() + 
                                        " AND ( MONTH( g.data ) =  " + jtxtMes.getText() + " AND YEAR( g.data) = " + jtxtAno.getText() + " ) " 
                        , "SUM(g.valor)", null) ); 
                
                 tot = new Funcoes().round( (Double)new Funcoes().retornar("SELECT SUM(g.valor)"
                                + " FROM gasto as g"
                                + " WHERE (( MONTH( g.data ) =  " + jtxtMes.getText() + ") AND ( YEAR( g.data) = " + jtxtAno.getText() + " )) " 
                        , "SUM(g.valor)", null) ); 
         
                jtxtResultPess.setText(Double.toString(totPess));
                
                jtxtResult.setText(Double.toString(tot));
                
        
        }
        
       
        System.out.println();
        
        // Verifica se tem meta cadastrada dum dado mês do ano e armazena na variável a meta.
        
        
        String[][] parametro  = new String[3][2];
     
        parametro[0][0] = "Double";
                
        parametro[0][1] = jtxtCodigoPessoa.getText();
                
        parametro[1][0] = "Double";
                
        parametro[1][1] = jtxtMes.getText();
        
        parametro[2][0] = "Double";
                
        parametro[2][1] = jtxtAno.getText();
        
        
        if(new Funcoes().retornar("SELECT valor  "
                                + " FROM meta"
                                + " WHERE ( ( codigoPessoa = ? ) and ( mes = ? ) and ( ano = ? ) ) ", "valor", parametro) != null)
        
                meta = (Double)new Funcoes().retornar("SELECT valor  "
                                + " FROM meta"
                                + " WHERE ( ( codigoPessoa = ? ) and ( mes = ? ) and ( ano = ? ) ) ", "valor", parametro);
        
        // Verifica se cadastrou uma renda recebida num mês do ano e armazena na variável renda.
        
        if(new Funcoes().retornar("SELECT valor  "
                                + " FROM entradaCapital"
                                + " WHERE ( ( codigoPessoa = ? ) and ( mes = ? ) and ( ano = ? ) ) ", "valor", parametro) != null)
        
        
                renda = (Double)new Funcoes().retornar("SELECT valor  "
                                + " FROM entradaCapital"
                                + " WHERE ( ( codigoPessoa = ? ) and ( mes = ? ) and ( ano = ? ) ) ", "valor", parametro);
        
        // Caso  tiver cadastrado a meta.
        
        if(meta != 0 ) {
        
                    if (totPess  > meta) { // Caso não atingiu a meta setada.
            
                                jtxtSituacao.setText("Vermelho");
            
                                txtInfoMeta.setText("Não");
             
                    }
        
                    else { // Caso atingiu a meta setada.
           
                            jtxtSituacao.setText("Azul");
          
                            txtInfoMeta.setText("Sim");
            
                    }
        }
        
        // Caso não tiver meta cadastrada.
        
        if(renda != 0) {
        
            if (totPess > renda) // Caso gastou mais do que a renda disponível.
            
                jtxtSituacao.setBackground(Color.red);
        
            else // Caso gasto menos do que a renda disponível.
             
                jtxtSituacao.setBackground(Color.BLUE);
            
        }
     
        JOptionPane.showMessageDialog(null, "Processo de análise concluído com sucesso.", "System Message", JOptionPane.INFORMATION_MESSAGE);
         
       
        
    }//GEN-LAST:event_jmAnalisarMouseClicked

    private void jmMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmMenuMouseClicked
        // Vai para o menu principal e fecha o frame atual.
        
        MenuPrincipal.main(argumento,jtxtUsuario.getText());
        
        AnalisaGastos.this.dispose();
        
    }//GEN-LAST:event_jmMenuMouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // Verifico se posso liberar o botão de análise.
        
        if((jtxtMes.getText().isEmpty() == false) && (jtxtAno.getText().isEmpty() == false) && (jtxtCodigoPessoa.getText().isEmpty() == false) && (trava == false)   ) {
            
            trava = true;
            
            jmAnalisar.setVisible(true);
            
        }
        
        // Seta o código da pessoa se o login dela tiver poderes de usuário.
        
        if(new Funcoes().getTipoUsuario(jtxtUsuario.getText()).toString().compareTo("usuario") == 0) 
                
        {            
        
                    String[][] parametro = new String[1][2];
         
                    parametro[0][0] = "String";
        
                    parametro[0][1] = jtxtUsuario.getText();
        
                    jtxtCodigoPessoa.setText(new Funcoes().retornar("SELECT codigoPessoa FROM login WHERE usuario = ?", "codigoPessoa", parametro).toString());
        
        }
        
    }//GEN-LAST:event_formWindowActivated

    private void jtxtCodigoPessoaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtCodigoPessoaMouseClicked
        // Se for admin ou root poderá escolher o código da pessoa na lista.
        
        if( (new Funcoes().getTipoUsuario(jtxtUsuario.getText()).toString().compareTo("administrador") == 0) ||
                 (new Funcoes().getTipoUsuario(jtxtUsuario.getText()).toString().compareTo("root") == 0) )  
                
                 ListagemPessoa.main(argumento, jtxtCodigoPessoa, null,"Retorno de código", false, jtxtUsuario.getText(), "Selecione o código da pessoa que terá seus gastos análisados.");
        
        
    }//GEN-LAST:event_jtxtCodigoPessoaMouseClicked

    /**
     * @param args the command line arguments
    /**
     * @param args the command line arguments
     */
    
    
    public static void main(String args[], String user) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AnalisaGastos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AnalisaGastos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AnalisaGastos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AnalisaGastos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AnalisaGastos().setVisible(true);
                
                jtxtUsuario.setText(user);
               
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jmAnalisar;
    private javax.swing.JMenu jmLimpar;
    private javax.swing.JMenu jmMenu;
    private javax.swing.JMenuBar jmbMenu;
    private javax.swing.JPanel jpBase;
    private javax.swing.JPanel jpEntrada;
    private javax.swing.JPanel jpSaida;
    private javax.swing.JScrollPane jspFundo;
    private javax.swing.JTextField jtxtAno;
    public static javax.swing.JTextField jtxtCodigoPessoa;
    private javax.swing.JTextField jtxtDataHora;
    public static javax.swing.JTextField jtxtMes;
    public static javax.swing.JTextField jtxtResult;
    public static javax.swing.JTextField jtxtResultPess;
    private javax.swing.JTextField jtxtSituacao;
    private static javax.swing.JTextField jtxtUsuario;
    private javax.swing.JTextField txtInfoMeta;
    // End of variables declaration//GEN-END:variables
}
