/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package doug;

/**
 *
 * @author Douglas
 */




public class CadastroDivida extends javax.swing.JFrame {

    /**
     * Creates new form CadastroDivida
     */
    
    private String[] argumento;
    
    private boolean trava = false;

    
    
    public CadastroDivida() {
        initComponents();
  
        this.setExtendedState(MAXIMIZED_BOTH);
        
        new Funcoes().setaCodigo(jtxtCodigoDivida,"SELECT Max(codigo) "
                          + "FROM divida ","Max(codigo)");
        
        jmCadastro.setVisible(false);
 
       
        new Funcoes().executeTimer(jtxtDataHora, "dd/MM/yyyy hh:mm:ss");
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jspFundo = new javax.swing.JScrollPane();
        jpBase = new javax.swing.JPanel();
        jtxtCodigoDivida = new javax.swing.JTextField();
        jtxtCodigoPessoa = new javax.swing.JTextField();
        jtxtDescricao = new javax.swing.JTextField();
        jtxtValor = new javax.swing.JTextField();
        jtxtDataVence = new javax.swing.JTextField();
        jtxtUsuario = new javax.swing.JTextField();
        jtxtDataHora = new javax.swing.JTextField();
        jmbMenu = new javax.swing.JMenuBar();
        jmCadastro = new javax.swing.JMenu();
        jmMenu = new javax.swing.JMenu();
        jmLimpar = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro de dívidas");
        setBackground(new java.awt.Color(255, 102, 102));
        setForeground(java.awt.Color.white);
        setName("jfCadastroDiv"); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jpBase.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51), 5));
        jpBase.setPreferredSize(new java.awt.Dimension(1280, 750));

        jtxtCodigoDivida.setEditable(false);
        jtxtCodigoDivida.setBackground(new java.awt.Color(0, 0, 102));
        jtxtCodigoDivida.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jtxtCodigoDivida.setForeground(new java.awt.Color(153, 153, 0));
        jtxtCodigoDivida.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 0), 5, true), "Código da dívida", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 48), new java.awt.Color(255, 255, 204))); // NOI18N

        jtxtCodigoPessoa.setEditable(false);
        jtxtCodigoPessoa.setBackground(new java.awt.Color(0, 0, 102));
        jtxtCodigoPessoa.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jtxtCodigoPessoa.setForeground(new java.awt.Color(153, 153, 0));
        jtxtCodigoPessoa.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 0), 5, true), "Código da pessoa", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 48), new java.awt.Color(255, 255, 204))); // NOI18N
        jtxtCodigoPessoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtCodigoPessoaMouseClicked(evt);
            }
        });

        jtxtDescricao.setEditable(false);
        jtxtDescricao.setBackground(new java.awt.Color(0, 0, 102));
        jtxtDescricao.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jtxtDescricao.setForeground(new java.awt.Color(153, 153, 0));
        jtxtDescricao.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 0), 5, true), "Descrição", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 48), new java.awt.Color(255, 255, 204))); // NOI18N
        jtxtDescricao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtDescricaoMouseClicked(evt);
            }
        });

        jtxtValor.setEditable(false);
        jtxtValor.setBackground(new java.awt.Color(0, 0, 102));
        jtxtValor.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jtxtValor.setForeground(new java.awt.Color(153, 153, 0));
        jtxtValor.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 0), 5, true), "Valor", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 48), new java.awt.Color(255, 255, 204))); // NOI18N
        jtxtValor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtValorMouseClicked(evt);
            }
        });

        jtxtDataVence.setEditable(false);
        jtxtDataVence.setBackground(new java.awt.Color(0, 0, 102));
        jtxtDataVence.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jtxtDataVence.setForeground(new java.awt.Color(153, 153, 0));
        jtxtDataVence.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 0), 5, true), "Data de vencimento", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 48), new java.awt.Color(255, 255, 204))); // NOI18N
        jtxtDataVence.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtDataVenceMouseClicked(evt);
            }
        });

        jtxtUsuario.setEditable(false);
        jtxtUsuario.setBackground(new java.awt.Color(0, 0, 102));
        jtxtUsuario.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jtxtUsuario.setForeground(new java.awt.Color(153, 153, 0));
        jtxtUsuario.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 0), 5, true), "Usuário", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 48), new java.awt.Color(255, 255, 204))); // NOI18N

        jtxtDataHora.setEditable(false);
        jtxtDataHora.setBackground(new java.awt.Color(0, 0, 102));
        jtxtDataHora.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jtxtDataHora.setForeground(new java.awt.Color(153, 153, 0));
        jtxtDataHora.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 0), 5, true), "Data e Hora", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 48), new java.awt.Color(255, 255, 204))); // NOI18N

        javax.swing.GroupLayout jpBaseLayout = new javax.swing.GroupLayout(jpBase);
        jpBase.setLayout(jpBaseLayout);
        jpBaseLayout.setHorizontalGroup(
            jpBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpBaseLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpBaseLayout.createSequentialGroup()
                        .addComponent(jtxtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jtxtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpBaseLayout.createSequentialGroup()
                        .addComponent(jtxtCodigoDivida, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(jtxtCodigoPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jtxtDataVence, javax.swing.GroupLayout.PREFERRED_SIZE, 545, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpBaseLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(jpBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtxtDataHora, javax.swing.GroupLayout.PREFERRED_SIZE, 782, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 782, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(308, Short.MAX_VALUE))
        );
        jpBaseLayout.setVerticalGroup(
            jpBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpBaseLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtCodigoDivida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtCodigoPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(jtxtDataVence, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addGroup(jpBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70)
                .addComponent(jtxtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(jtxtDataHora, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jspFundo.setViewportView(jpBase);

        jmbMenu.setBackground(new java.awt.Color(255, 102, 102));
        jmbMenu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 153), 10));
        jmbMenu.setForeground(new java.awt.Color(255, 255, 102));

        jmCadastro.setBackground(new java.awt.Color(153, 0, 153));
        jmCadastro.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 51), 5, true));
        jmCadastro.setForeground(new java.awt.Color(102, 0, 102));
        jmCadastro.setText("Cadastro");
        jmCadastro.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jmCadastro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmCadastroMouseClicked(evt);
            }
        });
        jmbMenu.add(jmCadastro);

        jmMenu.setBackground(new java.awt.Color(153, 0, 153));
        jmMenu.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 51), 5, true));
        jmMenu.setForeground(new java.awt.Color(102, 0, 102));
        jmMenu.setText("Menu Principal");
        jmMenu.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jmMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmMenuMouseClicked(evt);
            }
        });
        jmbMenu.add(jmMenu);

        jmLimpar.setBackground(new java.awt.Color(153, 0, 153));
        jmLimpar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 51), 5, true));
        jmLimpar.setForeground(new java.awt.Color(102, 0, 102));
        jmLimpar.setText("Limpar");
        jmLimpar.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jmLimpar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmLimparMouseClicked(evt);
            }
        });
        jmbMenu.add(jmLimpar);

        setJMenuBar(jmbMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jspFundo, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jspFundo, javax.swing.GroupLayout.DEFAULT_SIZE, 712, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmLimparMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmLimparMouseClicked
        // Limpa o formulário.
  
        new Funcoes().setaCodigo(jtxtCodigoDivida,"SELECT Max(codigo) "
                          + "FROM divida ","Max(codigo)");
        
        jtxtCodigoDivida.setText("");
      
        jtxtValor.setText("");
      
        jtxtDescricao.setText("");
     
        jtxtDataVence.setText("");
        
        jtxtCodigoPessoa.setText("");
        
        trava = false;
        
        jmCadastro.setVisible(false);
   
      

    }//GEN-LAST:event_jmLimparMouseClicked

    private void jmMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmMenuMouseClicked
        // Vai para a tela de Menu Principal e fecha a tela atual.
        
        MenuPrincipal.main(argumento,jtxtUsuario.getText());
     
        CadastroDivida.this.dispose();
        
        
    }//GEN-LAST:event_jmMenuMouseClicked

    private void jtxtDescricaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtDescricaoMouseClicked
        // Vai para a tela de entrada.
        
         if(jtxtDescricao.getText().isEmpty() == true)
            
            EntradaValores.main(argumento, jtxtDescricao, false, jtxtUsuario.getText(), "Insira uma descrição resumida para sua dívida.");
        
    }//GEN-LAST:event_jtxtDescricaoMouseClicked

    private void jtxtValorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtValorMouseClicked
        // Chama a tela de entrada.
        
         if(jtxtValor.getText().isEmpty() == true)
            
            EntradaValores.main(argumento, jtxtValor, true, jtxtUsuario.getText(), "Insira o valor da dívida.");
        
    }//GEN-LAST:event_jtxtValorMouseClicked

    private void jtxtDataVenceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtDataVenceMouseClicked
        // Vai para a tela de calendário.
        
         if(jtxtDataVence.getText().isEmpty() == true)
        
            Data.main(argumento, jtxtDataVence, 1000, "Selecione a data em que a dívida foi contraída.", jtxtUsuario.getText());
        
    }//GEN-LAST:event_jtxtDataVenceMouseClicked

    private void jmCadastroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmCadastroMouseClicked
        // Trata do cadastro.
    
        jmCadastro.setVisible(false);
        
        String[][] parametro = new String[5][2];
            
        parametro[0][0] = "Date";
            
        parametro[0][1] = jtxtDataVence.getText();
            
        parametro[1][0] = "Double";
            
        parametro[1][1] = jtxtCodigoPessoa.getText();
            
        parametro[2][0] = parametro[1][0];
            
        parametro[2][1] = jtxtCodigoDivida.getText();
            
        parametro[3][0] = parametro[1][0];
            
        parametro[3][1] = jtxtValor.getText();
            
        parametro[4][0] = "String";
            
        parametro[4][1] = jtxtDescricao.getText();
           
        new Funcoes().executa("INSERT INTO divida(dataVence,codigoPessoa,codigo,valor, descricao) VALUES(?,?,?,?,?)", parametro, "Registro na tabela de dívidas realizado com sucesso. ");
        
            
        
    }//GEN-LAST:event_jmCadastroMouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // Verifico se posso liberar o botão de cadastro.
        
        if( (jtxtDescricao.getText().isEmpty() == false) &&  
            (jtxtValor.getText().isEmpty() == false) &&    
            (jtxtDataVence.getText().isEmpty() == false) && (trava == false)    ) {
            
                    trava = true;
                    
                    jmCadastro.setVisible(true);
            
        }
        
       
        // Seto o código da pessoa caso for usuário.
        
        if (new Funcoes().getTipoUsuario(jtxtUsuario.getText()).toString().compareTo("usuario") == 0) { 
                
                 
                    String[][] parametro = new String[1][2];
         
                    parametro[0][0] = "String";
        
                    parametro[0][1] = jtxtUsuario.getText();
        
                    jtxtCodigoPessoa.setText(new Funcoes().retornar("SELECT codigoPessoa FROM login WHERE usuario = ?", "codigoPessoa", parametro).toString());
        
                    
        }
        
        
    }//GEN-LAST:event_formWindowActivated

    private void jtxtCodigoPessoaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtCodigoPessoaMouseClicked
        // Se for admin ou root poderá escolher o código da pessoa na lista.
        
        if( (new Funcoes().getTipoUsuario(jtxtUsuario.getText()).toString().compareTo("administrador") == 0) ||
                 (new Funcoes().getTipoUsuario(jtxtUsuario.getText()).toString().compareTo("root") == 0) )  
                
                 ListagemPessoa.main(argumento, jtxtCodigoPessoa, null,"Retorno de código", false, jtxtUsuario.getText(), "Selecione o código da pessoa que terá seus gastos análisados.");
        
        
    }//GEN-LAST:event_jtxtCodigoPessoaMouseClicked

    /**
     * @param args the command line arguments
     */
   
    
    
    
    public static void main(String args[], String user) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroDivida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroDivida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroDivida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroDivida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroDivida().setVisible(true);
                
                jtxtUsuario.setText(user);
              
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jmCadastro;
    private javax.swing.JMenu jmLimpar;
    private javax.swing.JMenu jmMenu;
    private javax.swing.JMenuBar jmbMenu;
    private javax.swing.JPanel jpBase;
    private javax.swing.JScrollPane jspFundo;
    public static javax.swing.JTextField jtxtCodigoDivida;
    public static javax.swing.JTextField jtxtCodigoPessoa;
    private static javax.swing.JTextField jtxtDataHora;
    public static javax.swing.JTextField jtxtDataVence;
    public static javax.swing.JTextField jtxtDescricao;
    private static javax.swing.JTextField jtxtUsuario;
    public static javax.swing.JTextField jtxtValor;
    // End of variables declaration//GEN-END:variables
}
