/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package doug;


/**
 *
 * @author DOUGLASFERREIRAG
 */
public class CadastroGasto extends javax.swing.JFrame {

    /**
     * Creates new form cadastroGasto
     */
    
    private String[] argumento;
    
    private boolean trava = false;
    
    public CadastroGasto() {
        initComponents();
        
        this.setExtendedState(MAXIMIZED_BOTH);
        
        new Funcoes().setaCodigo(jtxtCodigoGasto,"SELECT Max(codigo) "
                          + "FROM gasto ","Max(codigo)");
        
        jmCadastro.setVisible(false);
        
        
        new Funcoes().executeTimer(jtxtDataHora, "dd/MM/yyyy hh:mm:ss");
       
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jspFundo = new javax.swing.JScrollPane();
        jpBase = new javax.swing.JPanel();
        jtxtData = new javax.swing.JTextField();
        jtxtCodigoGasto = new javax.swing.JTextField();
        jtxtValor = new javax.swing.JTextField();
        jtxtDesconto = new javax.swing.JTextField();
        jtxtDescricao = new javax.swing.JTextField();
        jtxtCodigoPessoa = new javax.swing.JTextField();
        jtxtUsuario = new javax.swing.JTextField();
        jtxtDataHora = new javax.swing.JTextField();
        jmbMenu = new javax.swing.JMenuBar();
        jmCadastro = new javax.swing.JMenu();
        jmLimpar = new javax.swing.JMenu();
        jmMenu = new javax.swing.JMenu();
        jmItem = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro de Gastos");
        setName("jfCadastroGasto"); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jspFundo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 153), 10));
        jspFundo.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N

        jtxtData.setEditable(false);
        jtxtData.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jtxtData.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 0, 153), 5), "Data", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 48), new java.awt.Color(0, 102, 102))); // NOI18N
        jtxtData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtDataMouseClicked(evt);
            }
        });

        jtxtCodigoGasto.setEditable(false);
        jtxtCodigoGasto.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jtxtCodigoGasto.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 0, 153), 5, true), "Código do gasto", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 48), new java.awt.Color(0, 102, 102))); // NOI18N

        jtxtValor.setEditable(false);
        jtxtValor.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jtxtValor.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 0, 153), 5), "Valor", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 48), new java.awt.Color(0, 102, 102))); // NOI18N
        jtxtValor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtValorMouseClicked(evt);
            }
        });

        jtxtDesconto.setEditable(false);
        jtxtDesconto.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jtxtDesconto.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 0, 153), 5), "Desconto", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 48), new java.awt.Color(0, 102, 102))); // NOI18N
        jtxtDesconto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtDescontoMouseClicked(evt);
            }
        });

        jtxtDescricao.setEditable(false);
        jtxtDescricao.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jtxtDescricao.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 0, 153), 5), "Descrição", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 48), new java.awt.Color(0, 102, 102))); // NOI18N
        jtxtDescricao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtDescricaoMouseClicked(evt);
            }
        });

        jtxtCodigoPessoa.setEditable(false);
        jtxtCodigoPessoa.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jtxtCodigoPessoa.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 0, 153), 5, true), "Código da pessoa", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 48), new java.awt.Color(0, 102, 102))); // NOI18N
        jtxtCodigoPessoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtCodigoPessoaMouseClicked(evt);
            }
        });

        jtxtUsuario.setEditable(false);
        jtxtUsuario.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jtxtUsuario.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 0, 153), 5), "Usuário", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 48), new java.awt.Color(0, 102, 102))); // NOI18N

        jtxtDataHora.setEditable(false);
        jtxtDataHora.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jtxtDataHora.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 0, 153), 5), "Data e Hora", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 48), new java.awt.Color(0, 102, 102))); // NOI18N

        javax.swing.GroupLayout jpBaseLayout = new javax.swing.GroupLayout(jpBase);
        jpBase.setLayout(jpBaseLayout);
        jpBaseLayout.setHorizontalGroup(
            jpBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpBaseLayout.createSequentialGroup()
                .addGroup(jpBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpBaseLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jpBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtCodigoGasto, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jpBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtData, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtCodigoPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jpBaseLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jtxtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 1122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpBaseLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jtxtDataHora, javax.swing.GroupLayout.PREFERRED_SIZE, 1122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 23, Short.MAX_VALUE))
        );
        jpBaseLayout.setVerticalGroup(
            jpBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpBaseLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jpBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtCodigoGasto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(jpBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jpBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtCodigoPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                .addComponent(jtxtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(jtxtDataHora, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        jspFundo.setViewportView(jpBase);

        jmbMenu.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 255, 204), 10, true));
        jmbMenu.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N

        jmCadastro.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 0, 0), 5, true));
        jmCadastro.setText("Cadastro");
        jmCadastro.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jmCadastro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmCadastroMouseClicked(evt);
            }
        });
        jmbMenu.add(jmCadastro);

        jmLimpar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 0, 0), 5, true));
        jmLimpar.setText("Limpar");
        jmLimpar.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jmLimpar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmLimparMouseClicked(evt);
            }
        });
        jmbMenu.add(jmLimpar);

        jmMenu.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 0, 0), 5, true));
        jmMenu.setText("Menu Principal");
        jmMenu.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jmMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmMenuMouseClicked(evt);
            }
        });
        jmbMenu.add(jmMenu);

        jmItem.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 0, 0), 5, true));
        jmItem.setText("Ítem");
        jmItem.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jmItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmItemMouseClicked(evt);
            }
        });
        jmbMenu.add(jmItem);

        setJMenuBar(jmbMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jspFundo, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jspFundo, javax.swing.GroupLayout.DEFAULT_SIZE, 712, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtDataMouseClicked
        // Vai para a tela de entrada de data.
     
        if(jtxtData.getText().isEmpty() == true)
        
            Data.main(argumento, jtxtData, 1000, "Selecione a data em que ocorreu o gasto.", jtxtUsuario.getText());
        
    }//GEN-LAST:event_jtxtDataMouseClicked

    private void jtxtValorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtValorMouseClicked
        // Vai para o frame de entrada .
        
       
        
        double desconto = 0.0;
        
        if(jtxtDesconto.getText().isEmpty() == false)
            
            desconto = Double.parseDouble(jtxtDesconto.getText());
        
        double soma = 0.0;
        
        String[][] pesquisa = new String[1][2];
        
        pesquisa[0][0] = "Double";
        
        pesquisa[0][1] = jtxtCodigoGasto.getText();
       
        
        if  (jtxtValor.getText().isEmpty() == true) {
            
             if (new Funcoes().retornar("select sum(total) from item where codigoGasto = ?", "sum(total)", pesquisa) == null) 
            
                        EntradaValores.main(argumento, jtxtValor, true, jtxtUsuario.getText(), "Insira o valor do gasto.");
        
            else {
            
                    soma = new Funcoes().round((Double) new Funcoes().retornar("select sum(total) from item where codigoGasto = ?", "sum(total)", pesquisa));
                    
                    jtxtValor.setText(Double.toString(soma -  desconto));
                    
            }
        
                   
            
        }
        
    }//GEN-LAST:event_jtxtValorMouseClicked

    private void jtxtDescontoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtDescontoMouseClicked
        // Vai para a tela de entrada .
        
        
        
        if(jtxtDesconto.getText().isEmpty() == true)
            
            EntradaValores.main(argumento, jtxtDesconto, true, jtxtUsuario.getText(), "Insira o desconto dado no gasto com compras.");
            
        
        
    }//GEN-LAST:event_jtxtDescontoMouseClicked

    private void jtxtDescricaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtDescricaoMouseClicked
        //Vai para a tela de entrada.
        
       
        
        if(jtxtDescricao.getText().isEmpty() == true)
            
            EntradaValores.main(argumento, jtxtDescricao, false, jtxtUsuario.getText(), "Insira uma descrição resumida para o gasto.");
            
    
        
    }//GEN-LAST:event_jtxtDescricaoMouseClicked

    private void jmLimparMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmLimparMouseClicked
        // Limpa o formulário.
        
        new Funcoes().setaCodigo(jtxtCodigoGasto,"SELECT Max(codigo) "
                          + "FROM gasto ","Max(codigo)");
        
        jtxtDescricao.setText("");
        
        jtxtValor.setText("");
        
        jtxtData.setText("");
        
        jtxtDesconto.setText("");
        
        jtxtCodigoPessoa.setText("");
        
        jmItem.setVisible(true);
        
        trava = false;
        
        jmCadastro.setVisible(false);
        
    }//GEN-LAST:event_jmLimparMouseClicked

    private void jmMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmMenuMouseClicked
        //Vai para o menu principal e fecha o frame atual.
        
        MenuPrincipal.main(argumento, jtxtUsuario.getText());

        CadastroGasto.this.dispose(); 
        
    }//GEN-LAST:event_jmMenuMouseClicked

    private void jmCadastroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmCadastroMouseClicked
        // Trata do cadastro.
        
       
            jmCadastro.setVisible(false);
        
            String[][] parametro = new String[6][2];
            
            parametro[0][0] = "Date";
            
            parametro[0][1] = jtxtData.getText();
            
            parametro[1][0] = "Double";
            
            parametro[1][1] = jtxtCodigoPessoa.getText();
            
            parametro[2][0] = parametro[1][0];
            
            parametro[2][1] = jtxtCodigoGasto.getText();
            
            parametro[3][0] = parametro[1][0];
            
            parametro[3][1] = jtxtValor.getText();
            
            parametro[4][0] = "String";
            
            parametro[4][1] = jtxtDescricao.getText();
            
            parametro[5][0] = parametro[1][0];
            
            parametro[5][1] = jtxtDesconto.getText();
           
            new Funcoes().executa("INSERT INTO gasto(data,codigoPessoa,codigo,valor, descricao,desconto) VALUES(?,?,?,?,?,?)", parametro, "Inserção na tabela de gastos realizada com sucesso.");
        
        
    }//GEN-LAST:event_jmCadastroMouseClicked

    private void jmItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmItemMouseClicked
        // Vai para a tela de cadastro de ítens.
        
        CadastroItem.main(argumento,jtxtUsuario.getText());
        
        CadastroGasto.this.dispose();
        
    }//GEN-LAST:event_jmItemMouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
         // Seto o código da pessoa caso for usuário.
        
        if (new Funcoes().getTipoUsuario(jtxtUsuario.getText()).toString().compareTo("usuario") == 0) { 
                
                    String[][] parametro = new String[1][2];
         
                    parametro[0][0] = "String";
        
                    parametro[0][1] = jtxtUsuario.getText();
        
                    jtxtCodigoPessoa.setText(new Funcoes().retornar("SELECT codigoPessoa FROM login WHERE usuario = ?", "codigoPessoa", parametro).toString());
        
                    
        }
        
        // Verifico se posso liberar o botão de cadastro de ítens.
        
        if(
                (jtxtValor.getText().isEmpty() == false) || (jtxtDesconto.getText().isEmpty() == false) ||
                
                (jtxtDescricao.getText().isEmpty() == false) || (jtxtData.getText().isEmpty() == false)
                
            )
            
                    jmItem.setVisible(false);
        
        // Verifico se posso liberar o botão de cadastro de gasto.
        
        if((jtxtDescricao.getText().isEmpty() == false) &&
            (jtxtDesconto.getText().isEmpty() == false) &&    
            (jtxtValor.getText().isEmpty() == false) &&    
            (jtxtData.getText().isEmpty() == false) &&
            (trava == false) && (jtxtCodigoPessoa.getText().isEmpty() == false) &&
            ( (Double.parseDouble(jtxtValor.getText())) >  (Double.parseDouble(jtxtDesconto.getText())) )    
              
             
            
             
            ) {
            
                    trava = true;
         
                    jmCadastro.setVisible(true);
        }
        
    }//GEN-LAST:event_formWindowActivated

    private void jtxtCodigoPessoaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtCodigoPessoaMouseClicked
        // Se for admin ou root poderá escolher o código da pessoa na lista.
        
        if( (new Funcoes().getTipoUsuario(jtxtUsuario.getText()).toString().compareTo("administrador") == 0) ||
                 (new Funcoes().getTipoUsuario(jtxtUsuario.getText()).toString().compareTo("root") == 0) )  
                
                 ListagemPessoa.main(argumento, jtxtCodigoPessoa, null,"Retorno de código", false, jtxtUsuario.getText(), "Selecione o código da pessoa que gastou.");
        
        
    }//GEN-LAST:event_jtxtCodigoPessoaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[], String user) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroGasto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroGasto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroGasto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroGasto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroGasto().setVisible(true);
                
                jtxtUsuario.setText(user);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jmCadastro;
    private javax.swing.JMenu jmItem;
    private javax.swing.JMenu jmLimpar;
    private javax.swing.JMenu jmMenu;
    private javax.swing.JMenuBar jmbMenu;
    private javax.swing.JPanel jpBase;
    private javax.swing.JScrollPane jspFundo;
    public static javax.swing.JTextField jtxtCodigoGasto;
    private javax.swing.JTextField jtxtCodigoPessoa;
    private javax.swing.JTextField jtxtData;
    private static javax.swing.JTextField jtxtDataHora;
    private javax.swing.JTextField jtxtDesconto;
    private javax.swing.JTextField jtxtDescricao;
    private static javax.swing.JTextField jtxtUsuario;
    private javax.swing.JTextField jtxtValor;
    // End of variables declaration//GEN-END:variables
}
