/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package doug;

import javax.swing.JOptionPane;

/**
 *
 * @author DOUGLASFERREIRAG
 */
public class EntradaValores extends javax.swing.JFrame {

    /**
     * Creates new form letras
    
    */
    
    
    private static javax.swing.JTextField jtxtReturn;

    private  javax.swing.table.DefaultTableModel dtm ;
    
    private char[] mai = {'A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z','Ç'};
    
    private char[] min = {'a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z','ç'};
    
    private char[] dig = {'0','1','2','3','4','5','6','7','8','9'};
    
    private char[] carac = {'-', '.'};
    
    private static boolean num;
    
    private static String titulo;
   
    private  void limpar(){ // Limpa a tabela.
        
      
         
        for(int i = 0; i < dtm.getRowCount(); i++){
             
                for(int j = 0; j< dtm.getColumnCount(); j++)
                   
                    dtm.setValueAt("", i, j);
             
        }
         
         
        
    }
    
    private void preencher(char[] let, int column){ // Preenchendo a tabela.
        
        for(int i = 0; i < let.length; i++)
        {
            
            dtm.setValueAt(let[i], i, column);
            
        }
        
    }
    
    
    
    public EntradaValores() {
        initComponents();
        
        this.setExtendedState(MAXIMIZED_BOTH);
        
        dtm = (javax.swing.table.DefaultTableModel)jtableEntradaDados.getModel();
      
        
        
        preencher(mai, 0);
        
        preencher(min,1);
        
        preencher(carac,2);
        
        preencher(dig,3);
     
        
        new Funcoes().executeTimer(jtxtDataHora, "dd/MM/yyyy hh:mm:ss");
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jspFundo = new javax.swing.JScrollPane();
        jpBase = new javax.swing.JPanel();
        jtxtVisor = new javax.swing.JTextField();
        jspNum = new javax.swing.JScrollPane();
        jtableEntradaDados = new javax.swing.JTable();
        jtxtUsuario = new javax.swing.JTextField();
        jtxtDataHora = new javax.swing.JTextField();
        jmbMenu = new javax.swing.JMenuBar();
        jmbClean = new javax.swing.JMenu();
        jmBackspace = new javax.swing.JMenu();
        jmEnter = new javax.swing.JMenu();
        jmSpace = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("jfEntradaValores"); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jpBase.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 102), 10, true));
        jpBase.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N

        jtxtVisor.setEditable(false);
        jtxtVisor.setBackground(new java.awt.Color(51, 0, 204));
        jtxtVisor.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jtxtVisor.setForeground(new java.awt.Color(51, 255, 0));
        jtxtVisor.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 0), 10, true), "Visor", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 48))); // NOI18N

        jtableEntradaDados.setBackground(new java.awt.Color(51, 0, 204));
        jtableEntradaDados.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));
        jtableEntradaDados.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jtableEntradaDados.setForeground(new java.awt.Color(51, 255, 0));
        jtableEntradaDados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Letras maiúsculas", "Letras minúsculas", "Caracter", "Números"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtableEntradaDados.setRowHeight(64);
        jtableEntradaDados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jtableEntradaDadosMousePressed(evt);
            }
        });
        jspNum.setViewportView(jtableEntradaDados);

        jtxtUsuario.setEditable(false);
        jtxtUsuario.setBackground(new java.awt.Color(51, 0, 204));
        jtxtUsuario.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jtxtUsuario.setForeground(new java.awt.Color(51, 255, 0));
        jtxtUsuario.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 0), 5), "Usuário", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 48))); // NOI18N

        jtxtDataHora.setEditable(false);
        jtxtDataHora.setBackground(new java.awt.Color(51, 0, 204));
        jtxtDataHora.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jtxtDataHora.setForeground(new java.awt.Color(51, 255, 0));
        jtxtDataHora.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 0), 5), "Data e Hora", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 48))); // NOI18N

        javax.swing.GroupLayout jpBaseLayout = new javax.swing.GroupLayout(jpBase);
        jpBase.setLayout(jpBaseLayout);
        jpBaseLayout.setHorizontalGroup(
            jpBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpBaseLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtxtVisor, javax.swing.GroupLayout.PREFERRED_SIZE, 699, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jspNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpBaseLayout.createSequentialGroup()
                        .addComponent(jtxtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jtxtDataHora, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(266, Short.MAX_VALUE))
        );
        jpBaseLayout.setVerticalGroup(
            jpBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpBaseLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jtxtVisor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jspNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                .addGroup(jpBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtDataHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(96, 96, 96))
        );

        jspFundo.setViewportView(jpBase);

        jmbMenu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 51), 10));
        jmbMenu.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N

        jmbClean.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 51, 0), 5));
        jmbClean.setText("Clean");
        jmbClean.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jmbClean.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmbCleanMouseClicked(evt);
            }
        });
        jmbMenu.add(jmbClean);

        jmBackspace.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 51, 0), 5));
        jmBackspace.setText("Backspace");
        jmBackspace.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jmBackspace.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmBackspaceMouseClicked(evt);
            }
        });
        jmbMenu.add(jmBackspace);

        jmEnter.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 51, 0), 5));
        jmEnter.setText("Enter");
        jmEnter.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jmEnter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmEnterMouseClicked(evt);
            }
        });
        jmbMenu.add(jmEnter);

        jmSpace.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 51, 0), 5));
        jmSpace.setText("Espaço");
        jmSpace.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jmSpace.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmSpaceMouseClicked(evt);
            }
        });
        jmbMenu.add(jmSpace);

        setJMenuBar(jmbMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jspFundo, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jspFundo, javax.swing.GroupLayout.DEFAULT_SIZE, 733, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // Limpa a tabela.
        
        limpar();
        
    }//GEN-LAST:event_formWindowClosed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // Troca o nome do frame.
        
        this.setTitle(titulo);
        
    }//GEN-LAST:event_formWindowActivated

    private void jtableEntradaDadosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtableEntradaDadosMousePressed
          // Exibe a letra selecionada na tela.
        
        if(num == true) {
            
            if(jtxtVisor.getText().isEmpty() == false) {
                
                    if(jtxtVisor.getText().indexOf('.') != -1) {
                        
                            
                            if (jtableEntradaDados.getSelectedColumn() == 3)
                                    
                                    jtxtVisor.setText(jtxtVisor.getText().concat(dtm.getValueAt(jtableEntradaDados.getSelectedRow(),jtableEntradaDados.getSelectedColumn()).toString()));
        
                        
                    }
                    
                    else{
            
                              if( (jtableEntradaDados.getSelectedColumn() == 3) || (dtm.getValueAt(jtableEntradaDados.getSelectedRow(),jtableEntradaDados.getSelectedColumn()).toString().compareTo(".") == 0) )
                
                                        jtxtVisor.setText(jtxtVisor.getText().concat(dtm.getValueAt(jtableEntradaDados.getSelectedRow(),jtableEntradaDados.getSelectedColumn()).toString()));
        
                    }
                    
                    
            }
            
            else
                        
                    {
                        
                            if (jtableEntradaDados.getSelectedColumn() == 3)
                                    
                                    jtxtVisor.setText(jtxtVisor.getText().concat(dtm.getValueAt(jtableEntradaDados.getSelectedRow(),jtableEntradaDados.getSelectedColumn()).toString()));
        
                        
                    }
         
        }
                
        
        else
            
        {
            
            if( (jtableEntradaDados.getSelectedColumn() != 3) && (dtm.getValueAt(jtableEntradaDados.getSelectedRow(),jtableEntradaDados.getSelectedColumn()).toString().compareTo(".") != 0) )
                
                jtxtVisor.setText(jtxtVisor.getText().concat(dtm.getValueAt(jtableEntradaDados.getSelectedRow(),jtableEntradaDados.getSelectedColumn()).toString()));
        
            
        }
            
            
    
        
        
        
    }//GEN-LAST:event_jtableEntradaDadosMousePressed

    private void jmSpaceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmSpaceMouseClicked
        // Da espaço caso clicada.
        
        if(num == false)
            
            jtxtVisor.setText(jtxtVisor.getText().concat(" "));
        
    }//GEN-LAST:event_jmSpaceMouseClicked

    private void jmBackspaceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmBackspaceMouseClicked
        // Remove o último caracter da caixa de texto.
        
        String visor = jtxtVisor.getText();
      
        visor = visor.substring(0, (visor.length() - 1));
        
        jtxtVisor.setText(visor);
        
    }//GEN-LAST:event_jmBackspaceMouseClicked

    private void jmbCleanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmbCleanMouseClicked
        // limpa o visor.
        
        jtxtVisor.setText("");
       
        
    }//GEN-LAST:event_jmbCleanMouseClicked

    private void jmEnterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmEnterMouseClicked
        // Retorna para onde foi chamado.
        
        if(jtxtVisor.getText().isEmpty() == false) {
            
            jtxtReturn.setText(jtxtVisor.getText());
        
            dispose();
            
        }
        
        else 
            
            JOptionPane.showMessageDialog(null, " Não inseriu nada na caixa de texto. ", "System Message", JOptionPane.INFORMATION_MESSAGE);
        
       
        
    }//GEN-LAST:event_jmEnterMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[] , javax.swing.JTextField jtxtR, boolean flag, String user, String title) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EntradaValores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EntradaValores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EntradaValores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EntradaValores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EntradaValores().setVisible(true);
                
                jtxtReturn = jtxtR;
                
                num = flag;
           
                jtxtUsuario.setText(user);
                
                titulo = title;
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jmBackspace;
    private javax.swing.JMenu jmEnter;
    private javax.swing.JMenu jmSpace;
    private javax.swing.JMenu jmbClean;
    private javax.swing.JMenuBar jmbMenu;
    private javax.swing.JPanel jpBase;
    private javax.swing.JScrollPane jspFundo;
    private javax.swing.JScrollPane jspNum;
    private javax.swing.JTable jtableEntradaDados;
    public static javax.swing.JTextField jtxtDataHora;
    public static javax.swing.JTextField jtxtUsuario;
    private javax.swing.JTextField jtxtVisor;
    // End of variables declaration//GEN-END:variables
}
