/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package doug;

import java.sql.Connection;

import java.sql.DriverManager;

import java.sql.ResultSet;

import java.sql.Statement;

import javax.swing.JOptionPane;

/**
 *
 * @author DOUGLASFERREIRAG
 */
public class ListagemFornecedor extends javax.swing.JFrame {

    /**
     * Creates new form ListagemPagamentos
     */
    
    private static String[] args;
    
    private static javax.swing.JTextField jtxtReturn, jtxtColumn;
    
    private static javax.swing.table.DefaultTableModel dtm ;
    
    private static String temp = "";
    
    private static String titulo;

    
    public ListagemFornecedor() {
        
        initComponents();
        
        this.setExtendedState(MAXIMIZED_BOTH);
        
        new Funcoes().executeTimer(jtxtDataHora, "dd/MM/yyyy hh:mm:ss");
        
    }
    
     private static void preenche (String driver, String url, String user, String password, String query){
     // Preenche a tabela.
     
        
        Connection conn = null;
    
        Statement st = null;
          
         
          
        jtFornecedor.setModel(new javax.swing.table.DefaultTableModel(
                         new Object [][] { }, new String [] {
        
                         "Código","Descrição", "Local" //Aqui eu nomeio as colunas da tabela de saída.    
                          
                         
                         }
        ));
          
         
        try
               
        {
                
                Class.forName(driver);
                
                conn = DriverManager.getConnection(url, user, password);
       
                // Our SQL SELECT query. 
                
                // If you only need a few columns, specify them by name instead of using "*".
                                                                                                                                            
               // Create the java statement.
                
               st = conn.createStatement();
       
                // Execute the query, and get a java resultset.
               
                ResultSet rs = st.executeQuery(query);
                
               // Iterate through the java resultset.
                
               while (rs.next())
                   
               {        
                   
                    
                   
                     dtm = (javax.swing.table.DefaultTableModel)jtFornecedor.getModel();

                    dtm.addRow(new Object[]{rs.getDouble("codigo"),rs.getString("descricao") ,rs.getString("local")  
                                            
                               });
                   
                     
                }
             
                st.close();
                
                conn.close();
            }
           
            catch (Exception e)
                
            {
                 System.err.println("Got an exception! ");
                 
                 System.err.println(e.getMessage());
                 
            }

                      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jspFundo = new javax.swing.JScrollPane();
        jpBase = new javax.swing.JPanel();
        jspSaida = new javax.swing.JScrollPane();
        jtFornecedor = new javax.swing.JTable();
        jtxtUsuario = new javax.swing.JTextField();
        jtxtDataHora = new javax.swing.JTextField();
        jmbMenu = new javax.swing.JMenuBar();
        jmMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("frmListagemPagamentos"); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jspFundo.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.yellow, 5));

        jspSaida.setBackground(new java.awt.Color(255, 255, 51));
        jspSaida.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 0), 5, true));
        jspSaida.setForeground(new java.awt.Color(51, 255, 153));

        jtFornecedor.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jtFornecedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtFornecedor.setCellSelectionEnabled(true);
        jtFornecedor.setRowHeight(60);
        jtFornecedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jtFornecedorMousePressed(evt);
            }
        });
        jspSaida.setViewportView(jtFornecedor);

        jtxtUsuario.setEditable(false);
        jtxtUsuario.setBackground(java.awt.Color.black);
        jtxtUsuario.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jtxtUsuario.setForeground(java.awt.Color.gray);
        jtxtUsuario.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.yellow, 5), "Usuário", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 48), java.awt.Color.darkGray)); // NOI18N

        jtxtDataHora.setEditable(false);
        jtxtDataHora.setBackground(java.awt.Color.black);
        jtxtDataHora.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jtxtDataHora.setForeground(java.awt.Color.gray);
        jtxtDataHora.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.yellow, 5), "Data e Hora", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 48), java.awt.Color.darkGray)); // NOI18N

        javax.swing.GroupLayout jpBaseLayout = new javax.swing.GroupLayout(jpBase);
        jpBase.setLayout(jpBaseLayout);
        jpBaseLayout.setHorizontalGroup(
            jpBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpBaseLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtxtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 1143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtDataHora, javax.swing.GroupLayout.PREFERRED_SIZE, 1143, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(67, Short.MAX_VALUE))
            .addGroup(jpBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jpBaseLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jspSaida, javax.swing.GroupLayout.DEFAULT_SIZE, 1200, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jpBaseLayout.setVerticalGroup(
            jpBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpBaseLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jtxtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 535, Short.MAX_VALUE)
                .addComponent(jtxtDataHora, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
            .addGroup(jpBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jpBaseLayout.createSequentialGroup()
                    .addGap(158, 158, 158)
                    .addComponent(jspSaida, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(203, Short.MAX_VALUE)))
        );

        jspFundo.setViewportView(jpBase);

        jmbMenu.setBackground(java.awt.Color.black);
        jmbMenu.setBorder(new javax.swing.border.LineBorder(java.awt.Color.yellow, 10, true));
        jmbMenu.setForeground(java.awt.Color.gray);

        jmMenu.setBackground(new java.awt.Color(0, 255, 153));
        jmMenu.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 153), 5, true));
        jmMenu.setForeground(new java.awt.Color(153, 0, 153));
        jmMenu.setText("Menu Principal");
        jmMenu.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jmMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmMenuMouseClicked(evt);
            }
        });
        jmbMenu.add(jmMenu);

        setJMenuBar(jmbMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jspFundo, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jspFundo, javax.swing.GroupLayout.DEFAULT_SIZE, 712, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmMenuMouseClicked
        // Vai para o menu principal e fecha o frame atual.

        MenuPrincipal.main(args,jtxtUsuario.getText());

        ListagemFornecedor.this.dispose();

    }//GEN-LAST:event_jmMenuMouseClicked

    private void jtFornecedorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtFornecedorMousePressed
        // Retornar um dado valor.

        dtm =  (javax.swing.table.DefaultTableModel)jtFornecedor.getModel();

        switch(temp){

            case "Alteração de dados":{

               
                    JOptionPane.showMessageDialog(null,"Valor na coluna selecionada: " + dtm.getValueAt(jtFornecedor.getSelectedRow() ,jtFornecedor.getSelectedColumn()).toString()+ "." , "System Message", JOptionPane.INFORMATION_MESSAGE);

                    jtxtReturn.setText(dtm.getValueAt(jtFornecedor.getSelectedRow() ,jtFornecedor.getSelectedColumn()).toString());

                    String nomeColuna = dtm.getColumnName(jtFornecedor.getSelectedColumn());
                            
                    JOptionPane.showMessageDialog(null,"Nome da coluna selecionada: " + nomeColuna + "." , "System Message", JOptionPane.INFORMATION_MESSAGE);
                
                    jtxtColumn.setText(nomeColuna);
                

                break;

            }

            case "Retorno de código": {

                if(jtFornecedor.getSelectedColumn() ==  0) {

                    JOptionPane.showMessageDialog(null,"Valor na coluna selecionada: " + dtm.getValueAt(jtFornecedor.getSelectedRow() ,0).toString() + "." , "System Message", JOptionPane.INFORMATION_MESSAGE);

                    jtxtReturn.setText(dtm.getValueAt(jtFornecedor.getSelectedRow() ,0).toString());

                }

                else

                    JOptionPane.showMessageDialog(null," Não selecionou a coluna do código do fornecedor.", "System Message", JOptionPane.INFORMATION_MESSAGE);

                break;

            }
            
            case "Captura de descrição":{
                
                    if(jtFornecedor.getSelectedColumn() ==  1) {

                            JOptionPane.showMessageDialog(null,"Valor na coluna selecionada: " + dtm.getValueAt(jtFornecedor.getSelectedRow() ,1).toString() + "." , "System Message", JOptionPane.INFORMATION_MESSAGE);

                            jtxtReturn.setText(dtm.getValueAt(jtFornecedor.getSelectedRow() ,1).toString());

                    }

                    else

                        JOptionPane.showMessageDialog(null," Não selecionou a coluna da descrição do fornecedor.", "System Message", JOptionPane.INFORMATION_MESSAGE);

                    break;

                
            }

            default:{

                JOptionPane.showMessageDialog(null,"Valor na coluna selecionada: " + dtm.getValueAt(jtFornecedor.getSelectedRow() ,jtFornecedor.getSelectedColumn()).toString() + "." , "System Message", JOptionPane.INFORMATION_MESSAGE);

                JOptionPane.showMessageDialog(null,"Nome da coluna selecionada: " + dtm.getColumnName(jtFornecedor.getSelectedColumn()) + "." , "System Message", JOptionPane.INFORMATION_MESSAGE);

                break;

            }

        }

        if( (temp.compareTo("Alteração de dados") == 0) || (temp.compareTo("Retorno de código") == 0) || (temp.compareTo("Captura de descrição") == 0))

            dispose();

    }//GEN-LAST:event_jtFornecedorMousePressed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // Troca o nome do frame.
        
        this.setTitle(titulo);
        
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[],javax.swing.JTextField txtRetorno,  javax.swing.JTextField txtColuna,String t, boolean ligar, String caption, String user) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListagemFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListagemFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListagemFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListagemFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListagemFornecedor().setVisible(true);
                
                preenche("org.gjt.mm.mysql.Driver","jdbc:mysql://localhost/gastos", "root", "","Select * from fornecedor Order by codigo asc" ) ; // Preenche a tabela.
            
                jtxtReturn  = txtRetorno;
          
                jtxtColumn = txtColuna;
                
                jmMenu.setVisible(ligar);
                
                temp = t;
                
                jtxtUsuario.setText(user);
                
                titulo = caption;
                 
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JMenu jmMenu;
    private javax.swing.JMenuBar jmbMenu;
    private javax.swing.JPanel jpBase;
    private javax.swing.JScrollPane jspFundo;
    private javax.swing.JScrollPane jspSaida;
    private static javax.swing.JTable jtFornecedor;
    private static javax.swing.JTextField jtxtDataHora;
    private static javax.swing.JTextField jtxtUsuario;
    // End of variables declaration//GEN-END:variables
}
