/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package doug;

import java.sql.*;

import javax.swing.JOptionPane;

/**
 *
 * @author Douglas
 */



public class ListagemPessoa extends javax.swing.JFrame {

    /**
     * Creates new form RegistroPessoa
     */
    
    private String[] args;
    
    private static javax.swing.JTextField jtxtReturn,jtxtColumn;
    
    private static javax.swing.table.DefaultTableModel dtm ;
    
    private static String temp = "";
  
    private static String titulo;
    
    public ListagemPessoa() {
        
    
        initComponents();
        
        this.setExtendedState(MAXIMIZED_BOTH);
        
        new Funcoes().executeTimer(jtxtDataHora, "dd/MM/yyyy hh:mm:ss");
        
        
    }
    
    private static void tabela(){ // Constrói a tabela com base nas restrições pedidas.
        
             if( (new Funcoes().getTipoUsuario(jtxtUsuario.getText()).toString().compareTo("administrador") == 0) ||
                    (new Funcoes().getTipoUsuario(jtxtUsuario.getText()).toString().compareTo("root") == 0) )
                   
                    preenche("org.gjt.mm.mysql.Driver","jdbc:mysql://localhost/gastos", "root", "","Select * from pessoa Order by codigo asc" ) ; // Preenche a tabela.
            
            else
                
            {
            
                String[][] parametro = new String[1][2];
                
                parametro[0][0] = "String";
                
                parametro[0][1] = jtxtUsuario.getText();
                
                
                preenche("org.gjt.mm.mysql.Driver","jdbc:mysql://localhost/gastos", "root", "",
                        
                            "Select * from pessoa where codigo = " + new Funcoes().retornar("SELECT codigoPessoa FROM login WHERE usuario = ?", "codigoPessoa", parametro) + 
                        
                                "Order by codigo asc" ) ; // Preenche a tabela.
            
                
                
            }
            
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jspFundo = new javax.swing.JScrollPane();
        jpBase = new javax.swing.JPanel();
        jtxtUsuario = new javax.swing.JTextField();
        jspResultado = new javax.swing.JScrollPane();
        jtPessoas = new javax.swing.JTable();
        jtxtDataHora = new javax.swing.JTextField();
        jmbMenu = new javax.swing.JMenuBar();
        jmMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Listagem de pessoas");
        setBackground(new java.awt.Color(153, 255, 153));
        setForeground(java.awt.Color.cyan);
        setName("jfListagemPessoa"); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jtxtUsuario.setEditable(false);
        jtxtUsuario.setBackground(new java.awt.Color(153, 255, 102));
        jtxtUsuario.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jtxtUsuario.setForeground(new java.awt.Color(102, 0, 102));
        jtxtUsuario.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 102, 0), 5), "Usuário", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 48))); // NOI18N

        jspResultado.setBackground(new java.awt.Color(204, 255, 51));
        jspResultado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 153), 5));

        jtPessoas.setBackground(new java.awt.Color(255, 255, 51));
        jtPessoas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 0), 5));
        jtPessoas.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jtPessoas.setForeground(new java.awt.Color(51, 0, 51));
        jtPessoas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtPessoas.setRowHeight(60);
        jtPessoas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jtPessoasMousePressed(evt);
            }
        });
        jspResultado.setViewportView(jtPessoas);

        jtxtDataHora.setEditable(false);
        jtxtDataHora.setBackground(new java.awt.Color(153, 255, 102));
        jtxtDataHora.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jtxtDataHora.setForeground(new java.awt.Color(102, 0, 102));
        jtxtDataHora.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 102, 0), 5), "Data e Hora", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 48))); // NOI18N

        javax.swing.GroupLayout jpBaseLayout = new javax.swing.GroupLayout(jpBase);
        jpBase.setLayout(jpBaseLayout);
        jpBaseLayout.setHorizontalGroup(
            jpBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpBaseLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtxtUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 1782, Short.MAX_VALUE)
                    .addComponent(jtxtDataHora)
                    .addComponent(jspResultado, javax.swing.GroupLayout.DEFAULT_SIZE, 1782, Short.MAX_VALUE))
                .addContainerGap())
        );
        jpBaseLayout.setVerticalGroup(
            jpBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpBaseLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jtxtDataHora, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jspResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addComponent(jtxtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jspFundo.setViewportView(jpBase);

        jmbMenu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 255), 10));
        jmbMenu.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N

        jmMenu.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 0), 5, true));
        jmMenu.setText("Menu Principal");
        jmMenu.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jmMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmMenuMouseClicked(evt);
            }
        });
        jmbMenu.add(jmMenu);

        setJMenuBar(jmbMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jspFundo, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jspFundo, javax.swing.GroupLayout.DEFAULT_SIZE, 712, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmMenuMouseClicked
        // Vai para o menu principal e fecha o frame atual.

        MenuPrincipal.main(args, jtxtUsuario.getText());

        ListagemPessoa.this.dispose();

    }//GEN-LAST:event_jmMenuMouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // Troca o nome do frame.
        
        this.setTitle(titulo);
        
    }//GEN-LAST:event_formWindowActivated

    private void jtPessoasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtPessoasMousePressed
         // Retornar um dado valor.
        
        dtm =  (javax.swing.table.DefaultTableModel)jtPessoas.getModel();
        
        switch(temp){
                
                case "Alteração de dados":{
                    
                    JOptionPane.showMessageDialog(null,"Valor na coluna selecionada: " + dtm.getValueAt(jtPessoas.getSelectedRow() ,jtPessoas.getSelectedColumn()).toString() + "." , "System Message", JOptionPane.INFORMATION_MESSAGE);
                
                    jtxtReturn.setText(dtm.getValueAt(jtPessoas.getSelectedRow() ,jtPessoas.getSelectedColumn()).toString());
                
                    String nomeColuna = dtm.getColumnName(jtPessoas.getSelectedColumn());
                            
                    JOptionPane.showMessageDialog(null,"Nome da coluna selecionada: " + nomeColuna + "." , "System Message", JOptionPane.INFORMATION_MESSAGE);
                
                    jtxtColumn.setText(nomeColuna);
                    
                    break;
                    
                }
                
                case "Retorno de código": {
                    
                    if(jtPessoas.getSelectedColumn() ==  0) {
                    
                            JOptionPane.showMessageDialog(null,"Valor na coluna selecionada: " + dtm.getValueAt(jtPessoas.getSelectedRow() ,0).toString() + "." , "System Message", JOptionPane.INFORMATION_MESSAGE);
                
                            jtxtReturn.setText(dtm.getValueAt(jtPessoas.getSelectedRow() ,0).toString());
                    
                    }
                
                    else
                    
                        JOptionPane.showMessageDialog(null," Não selecionou a coluna do código.", "System Message", JOptionPane.INFORMATION_MESSAGE);
                
                    break;
                    
                }
                
                default:{
                    
                    JOptionPane.showMessageDialog(null,"Valor na coluna selecionada: " + dtm.getValueAt(jtPessoas.getSelectedRow() ,jtPessoas.getSelectedColumn()).toString() + "." , "System Message", JOptionPane.INFORMATION_MESSAGE);
            
                    JOptionPane.showMessageDialog(null,"Nome da coluna selecionada: " + dtm.getColumnName(jtPessoas.getSelectedColumn()) + "." , "System Message", JOptionPane.INFORMATION_MESSAGE);
        
                    break;
                    
                }
                
            }
            
            if( (temp.compareTo("Alteração de dados") == 0) || (temp.compareTo("Retorno de código") == 0) )
        
                dispose();
        
    }//GEN-LAST:event_jtPessoasMousePressed

    /**
     * @param args the command line arguments
     */
    
    
    private static void preenche (String driver, String url, String user, String password, String query){
     // Preenche a tabela.
     
        
        Connection conn = null;
    
        Statement st = null;
          
         
          
        jtPessoas.setModel(new javax.swing.table.DefaultTableModel(
                         new Object [][] { }, new String [] {
        //Aqui adiciona-se as colunas e seus respectivos nomes.
                         "Código","Nome Completo"
                         }
        ));
          
         
        try
               
        {
                
                Class.forName(driver);
                
                conn = DriverManager.getConnection(url, user, password);
                
                // Our SQL SELECT query. 
                
                // If you only need a few columns, specify them by name instead of using "*".
                                                                                                                                            
                // Create the java statement.
                
                st = conn.createStatement();
       
                // Execute the query, and get a java resultset.
               
                ResultSet rs = st.executeQuery(query);
                
                // Iterate through the java resultset.
                
                while (rs.next())
                   
                {                                  
                   
                    dtm = (javax.swing.table.DefaultTableModel)jtPessoas.getModel();

                    dtm.addRow(new Object[]{rs.getDouble("codigo"),rs.getString("nomeCompleto")});
                   
                     
                }
             
                st.close();
                
                conn.close();
        }
           
        catch (Exception e)
                
        {
            
                System.err.println("Got an exception! ");
                 
                System.err.println(e.getMessage());
                
                 
        }

                      
    }
     
   
    
    public static void main(String args[], javax.swing.JTextField txtRet,  javax.swing.JTextField txtColuna, String t, boolean ligar, String user, String caption ) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListagemPessoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListagemPessoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListagemPessoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListagemPessoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListagemPessoa().setVisible(true);
                
                jtxtUsuario.setText(user);
                
                jtxtReturn  = txtRet;
                
                jmMenu.setVisible(ligar);
                
                jtxtColumn = txtColuna;
                
                temp = t;
                
                titulo = caption;
                
                tabela();
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JMenu jmMenu;
    private javax.swing.JMenuBar jmbMenu;
    private javax.swing.JPanel jpBase;
    private javax.swing.JScrollPane jspFundo;
    private javax.swing.JScrollPane jspResultado;
    private static javax.swing.JTable jtPessoas;
    private static javax.swing.JTextField jtxtDataHora;
    private static javax.swing.JTextField jtxtUsuario;
    // End of variables declaration//GEN-END:variables
}
