/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package doug;

/**
 *
 * @author Douglas
 */

import java.sql.*;

import javax.swing.JOptionPane;


public class ListagemLogin extends javax.swing.JFrame {

    /**
     * Creates new form ListLogin
     */
    
    private String[] args;
    
    private static javax.swing.JTextField jtxtReturn, jtxtColumn;
    
    private static javax.swing.table.DefaultTableModel dtm ;
    
    private static String temp = "";
    
    private static String titulo;

    public ListagemLogin() {
        initComponents();
        
        this.setExtendedState(MAXIMIZED_BOTH);
        
        new Funcoes().executeTimer(jtxtDataHora, "dd/MM/yyyy hh:mm:ss");
        
        
        
    }
    
    private static void tabela(){
        
             if( (new Funcoes().getTipoUsuario(jtxtUsuario.getText()).toString().compareTo("administrador") == 0) ||
                    (new Funcoes().getTipoUsuario(jtxtUsuario.getText()).toString().compareTo("root") == 0) )
                  
                    preenche("org.gjt.mm.mysql.Driver","jdbc:mysql://localhost/gastos", "root", "","Select * from login Order by codigoPessoa asc" ) ; // Preenche a tabela.
            
           
            
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jspFundo = new javax.swing.JScrollPane();
        jpBase = new javax.swing.JPanel();
        jspSaida = new javax.swing.JScrollPane();
        jtLogins = new javax.swing.JTable();
        jtxtUsuario = new javax.swing.JTextField();
        jtxtDataHora = new javax.swing.JTextField();
        jmbMenu = new javax.swing.JMenuBar();
        jmMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("jfLoginRegister"); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jspFundo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 51), 5));

        jspSaida.setBackground(new java.awt.Color(255, 255, 51));
        jspSaida.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 0), 5, true));
        jspSaida.setForeground(new java.awt.Color(51, 255, 153));

        jtLogins.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jtLogins.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtLogins.setCellSelectionEnabled(true);
        jtLogins.setRowHeight(60);
        jtLogins.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jtLoginsMousePressed(evt);
            }
        });
        jspSaida.setViewportView(jtLogins);
        jtLogins.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        jtxtUsuario.setEditable(false);
        jtxtUsuario.setBackground(new java.awt.Color(255, 0, 51));
        jtxtUsuario.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jtxtUsuario.setForeground(new java.awt.Color(0, 51, 102));
        jtxtUsuario.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 0), 5), "Usuário", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 48), new java.awt.Color(102, 153, 0))); // NOI18N

        jtxtDataHora.setEditable(false);
        jtxtDataHora.setBackground(new java.awt.Color(255, 0, 51));
        jtxtDataHora.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jtxtDataHora.setForeground(new java.awt.Color(0, 51, 102));
        jtxtDataHora.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 0), 5), "Data e Hora", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 48), new java.awt.Color(102, 153, 0))); // NOI18N

        javax.swing.GroupLayout jpBaseLayout = new javax.swing.GroupLayout(jpBase);
        jpBase.setLayout(jpBaseLayout);
        jpBaseLayout.setHorizontalGroup(
            jpBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpBaseLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtxtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 1143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtDataHora, javax.swing.GroupLayout.PREFERRED_SIZE, 1143, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(67, Short.MAX_VALUE))
            .addGroup(jpBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jpBaseLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jspSaida, javax.swing.GroupLayout.DEFAULT_SIZE, 1200, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jpBaseLayout.setVerticalGroup(
            jpBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpBaseLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jtxtDataHora, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 535, Short.MAX_VALUE)
                .addComponent(jtxtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
            .addGroup(jpBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jpBaseLayout.createSequentialGroup()
                    .addGap(158, 158, 158)
                    .addComponent(jspSaida, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(314, Short.MAX_VALUE)))
        );

        jspFundo.setViewportView(jpBase);

        jmbMenu.setBackground(new java.awt.Color(153, 153, 255));
        jmbMenu.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 102, 0), 10, true));
        jmbMenu.setForeground(new java.awt.Color(102, 255, 102));

        jmMenu.setBackground(new java.awt.Color(0, 255, 153));
        jmMenu.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 153), 5, true));
        jmMenu.setForeground(new java.awt.Color(153, 0, 153));
        jmMenu.setText("Menu Principal");
        jmMenu.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jmMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmMenuMouseClicked(evt);
            }
        });
        jmbMenu.add(jmMenu);

        setJMenuBar(jmbMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jspFundo, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jspFundo, javax.swing.GroupLayout.DEFAULT_SIZE, 712, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmMenuMouseClicked
        // Vai para o menu principal e fecha o frame atual.

        MenuPrincipal.main(args,jtxtUsuario.getText());

        ListagemLogin.this.dispose(); 
        
    }//GEN-LAST:event_jmMenuMouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // Troca o nome do frame.
        
        this.setTitle(titulo);
        
    }//GEN-LAST:event_formWindowActivated

    private void jtLoginsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtLoginsMousePressed
         // Retornar um dado valor.
        
        dtm =  (javax.swing.table.DefaultTableModel)jtLogins.getModel();
        
        switch(temp){
                
                case "Alteração de dados":{
                    
                     if((jtLogins.getSelectedColumn() != 0) && (dtm.getValueAt(jtLogins.getSelectedRow() , 3).toString()).compareTo("root") != 0) {
                    
                            JOptionPane.showMessageDialog(null,"Valor na coluna selecionada: " + dtm.getValueAt(jtLogins.getSelectedRow() ,jtLogins.getSelectedColumn()).toString()+ "." , "System Message", JOptionPane.INFORMATION_MESSAGE);
                
                            jtxtReturn.setText(dtm.getValueAt(jtLogins.getSelectedRow() ,jtLogins.getSelectedColumn()).toString());
                
                            String nomeColuna = dtm.getColumnName(jtLogins.getSelectedColumn());
                            
                            JOptionPane.showMessageDialog(null,"Nome da coluna selecionada: " + nomeColuna + "." , "System Message", JOptionPane.INFORMATION_MESSAGE);
                
                            jtxtColumn.setText(nomeColuna);
                            
                            
                    }  
                     
                    break;
                    
                }
                
                case "Retorno de código": {
                    
                    if(jtLogins.getSelectedColumn() ==  0) {
                    
                            JOptionPane.showMessageDialog(null,"Valor na coluna selecionada: " + dtm.getValueAt(jtLogins.getSelectedRow() ,0).toString() + "." , "System Message", JOptionPane.INFORMATION_MESSAGE);
                
                            jtxtReturn.setText(dtm.getValueAt(jtLogins.getSelectedRow() ,0).toString());
                    
                    }
                
                    else
                    
                        JOptionPane.showMessageDialog(null," Não selecionou a coluna do código da pessoa.", "System Message", JOptionPane.INFORMATION_MESSAGE);
                
                    break;
                    
                }
                
                default:{
                    
                    JOptionPane.showMessageDialog(null,"Valor na coluna selecionada: " + dtm.getValueAt(jtLogins.getSelectedRow() ,jtLogins.getSelectedColumn()).toString() + "." , "System Message", JOptionPane.INFORMATION_MESSAGE);
            
                    JOptionPane.showMessageDialog(null,"Nome da coluna selecionada: " + dtm.getColumnName(jtLogins.getSelectedColumn()) + "." , "System Message", JOptionPane.INFORMATION_MESSAGE);
                    
                    break;
                    
                    
                }
                
            }
        
            if( (temp.compareTo("Alteração de dados") == 0) || (temp.compareTo("Retorno de código") == 0) )
        
                dispose();
            
    }//GEN-LAST:event_jtLoginsMousePressed

    /**
     * @param args the command line arguments
     */
    
   private static void preenche (String driver, String url, String user, String password, String query){
     // Preenche a tabela.
     
        
        Connection conn = null;
    
        Statement st = null;
          
         
          
        jtLogins.setModel(new javax.swing.table.DefaultTableModel(
                         new Object [][] { }, new String [] {
        
                         "Código da pessoa","Usuário", "Senha", "Tipo" //Aqui eu nomeio as colunas da tabela de saída.    
                         }
        ));
          
         
        try
               
        {
                
                Class.forName(driver);
                
                conn = DriverManager.getConnection(url, user, password);
       
                // Our SQL SELECT query. 
                
                // If you only need a few columns, specify them by name instead of using "*".
                                                                                                                                            
               // Create the java statement.
                
               st = conn.createStatement();
       
                // Execute the query, and get a java resultset.
               
                ResultSet rs = st.executeQuery(query);
                
               // Iterate through the java resultset.
                
               while (rs.next())
                   
               {        
                   
                    
                   
                     dtm = (javax.swing.table.DefaultTableModel)jtLogins.getModel();

                    dtm.addRow(new Object[]{rs.getDouble("codigoPessoa"),rs.getString("usuario"),rs.getString("senha"), rs.getString("poderes")
                               });
                   
                     
                }
             
                st.close();
                
                conn.close();
            }
           
            catch (Exception e)
                
            {
                 System.err.println("Got an exception! ");
                 
                 System.err.println(e.getMessage());
                 
            }

                      
    }
    
    
    public static void main(String args[], javax.swing.JTextField txtRetorno,  javax.swing.JTextField txtColuna,String t, boolean ligar, String caption, String user) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListagemLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListagemLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListagemLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListagemLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListagemLogin().setVisible(true);
                
                jtxtReturn  = txtRetorno;
          
                jtxtColumn = txtColuna;
                
                jmMenu.setVisible(ligar);
                
                temp = t;
                
                jtxtUsuario.setText(user);
                
                titulo = caption;
                
                tabela();
                 
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JMenu jmMenu;
    private javax.swing.JMenuBar jmbMenu;
    private javax.swing.JPanel jpBase;
    private javax.swing.JScrollPane jspFundo;
    private javax.swing.JScrollPane jspSaida;
    private static javax.swing.JTable jtLogins;
    private static javax.swing.JTextField jtxtDataHora;
    private static javax.swing.JTextField jtxtUsuario;
    // End of variables declaration//GEN-END:variables
}
