/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package doug;

/**
 *
 * @author DOUGLASFERREIRAG
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form menuPrincipal
     */
    
    private String[] argumento;
 
    
    public MenuPrincipal() {
        
        initComponents();
        
        this.setExtendedState(MAXIMIZED_BOTH);
        
        new Funcoes().executeTimer(jtxtDataHora, "dd/MM/yyyy hh:mm:ss");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jspFundo = new javax.swing.JScrollPane();
        jpBase = new javax.swing.JPanel();
        jtxtUsuario = new javax.swing.JTextField();
        jtxtDataHora = new javax.swing.JTextField();
        jmbPrincipal = new javax.swing.JMenuBar();
        jmEntradaSaida = new javax.swing.JMenu();
        jmiAnalise = new javax.swing.JMenuItem();
        jmiBalanceteSelecionado = new javax.swing.JMenuItem();
        jmGasto = new javax.swing.JMenu();
        jmiCadastroGast = new javax.swing.JMenuItem();
        jmiRemoveGast = new javax.swing.JMenuItem();
        jmiAlteraGast = new javax.swing.JMenuItem();
        jmiListaGast = new javax.swing.JMenuItem();
        jmItemGasto = new javax.swing.JMenu();
        jmiRemoveItem = new javax.swing.JMenuItem();
        jmiAlteraItem = new javax.swing.JMenuItem();
        jmiListaItem = new javax.swing.JMenuItem();
        jmDivida = new javax.swing.JMenu();
        jmiCadastroDiv = new javax.swing.JMenuItem();
        jmiRemoveDiv = new javax.swing.JMenuItem();
        jmiAlteraDiv = new javax.swing.JMenuItem();
        jmiListaDiv = new javax.swing.JMenuItem();
        jmEntradaCapital = new javax.swing.JMenu();
        jmiCadastroEntradaCapital = new javax.swing.JMenuItem();
        jmiRemoveEntradaCapital = new javax.swing.JMenuItem();
        jmiAlteraEntradaCapital = new javax.swing.JMenuItem();
        jmiListaEntradaCapital = new javax.swing.JMenuItem();
        jmMetas = new javax.swing.JMenu();
        jmiCadastro = new javax.swing.JMenuItem();
        jmiRemocao = new javax.swing.JMenuItem();
        jmiAlteracao = new javax.swing.JMenuItem();
        jmiListagemMetas = new javax.swing.JMenuItem();
        jmCatalogo = new javax.swing.JMenu();
        jmiCadastroCat = new javax.swing.JMenuItem();
        jmiRemoveCat = new javax.swing.JMenuItem();
        jmiAlteraCat = new javax.swing.JMenuItem();
        jmiListaCat = new javax.swing.JMenuItem();
        jmPessoa = new javax.swing.JMenu();
        jmiCadastroPess = new javax.swing.JMenuItem();
        jmiRemovePess = new javax.swing.JMenuItem();
        jmiAlteraPess = new javax.swing.JMenuItem();
        jmiListaPess = new javax.swing.JMenuItem();
        jmLogin = new javax.swing.JMenu();
        jmiCadastroLog = new javax.swing.JMenuItem();
        jmiRemoveLog = new javax.swing.JMenuItem();
        jmiAlteraLog = new javax.swing.JMenuItem();
        jmiListaLog = new javax.swing.JMenuItem();
        jmFornecedor = new javax.swing.JMenu();
        jmiCadastroFornecedor = new javax.swing.JMenuItem();
        jmiRemoveFornecedor = new javax.swing.JMenuItem();
        jmiAlteraFornecedor = new javax.swing.JMenuItem();
        jmiListaFornecedor = new javax.swing.JMenuItem();
        jmSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Principal");
        setBackground(new java.awt.Color(255, 0, 51));
        setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        setForeground(new java.awt.Color(0, 153, 153));
        setName("jfMenu"); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jspFundo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 102), 10, true));

        jtxtUsuario.setEditable(false);
        jtxtUsuario.setBackground(new java.awt.Color(51, 0, 51));
        jtxtUsuario.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jtxtUsuario.setForeground(new java.awt.Color(102, 102, 0));
        jtxtUsuario.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 153, 0), 5), "Usuário", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 48), new java.awt.Color(51, 51, 0))); // NOI18N

        jtxtDataHora.setEditable(false);
        jtxtDataHora.setBackground(new java.awt.Color(51, 0, 51));
        jtxtDataHora.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jtxtDataHora.setForeground(new java.awt.Color(102, 102, 0));
        jtxtDataHora.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 153, 0), 5), "Data e Hora", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 48), new java.awt.Color(51, 51, 0))); // NOI18N

        javax.swing.GroupLayout jpBaseLayout = new javax.swing.GroupLayout(jpBase);
        jpBase.setLayout(jpBaseLayout);
        jpBaseLayout.setHorizontalGroup(
            jpBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpBaseLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jtxtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jtxtDataHora, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(485, Short.MAX_VALUE))
        );
        jpBaseLayout.setVerticalGroup(
            jpBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpBaseLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jpBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtDataHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(1075, Short.MAX_VALUE))
        );

        jspFundo.setViewportView(jpBase);

        jmbPrincipal.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 255), 10, true));
        jmbPrincipal.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N

        jmEntradaSaida.setBackground(new java.awt.Color(51, 255, 51));
        jmEntradaSaida.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0), 5));
        jmEntradaSaida.setForeground(new java.awt.Color(51, 0, 51));
        jmEntradaSaida.setText("Entrada/Saida");
        jmEntradaSaida.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N

        jmiAnalise.setBackground(new java.awt.Color(0, 153, 255));
        jmiAnalise.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jmiAnalise.setForeground(new java.awt.Color(255, 102, 102));
        jmiAnalise.setText("Análise");
        jmiAnalise.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 102), 6));
        jmiAnalise.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jmiAnaliseMousePressed(evt);
            }
        });
        jmEntradaSaida.add(jmiAnalise);

        jmiBalanceteSelecionado.setBackground(new java.awt.Color(0, 153, 255));
        jmiBalanceteSelecionado.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jmiBalanceteSelecionado.setForeground(new java.awt.Color(255, 102, 102));
        jmiBalanceteSelecionado.setText("Balancete Selecionado");
        jmiBalanceteSelecionado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 102), 6));
        jmiBalanceteSelecionado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jmiBalanceteSelecionadoMousePressed(evt);
            }
        });
        jmEntradaSaida.add(jmiBalanceteSelecionado);

        jmGasto.setBackground(new java.awt.Color(51, 255, 51));
        jmGasto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0), 5));
        jmGasto.setForeground(new java.awt.Color(51, 0, 51));
        jmGasto.setText("Gasto");
        jmGasto.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N

        jmiCadastroGast.setBackground(new java.awt.Color(0, 153, 255));
        jmiCadastroGast.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jmiCadastroGast.setForeground(new java.awt.Color(255, 102, 102));
        jmiCadastroGast.setText("Cadastro");
        jmiCadastroGast.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 102), 6));
        jmiCadastroGast.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jmiCadastroGastMousePressed(evt);
            }
        });
        jmGasto.add(jmiCadastroGast);

        jmiRemoveGast.setBackground(new java.awt.Color(0, 153, 255));
        jmiRemoveGast.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jmiRemoveGast.setForeground(new java.awt.Color(255, 102, 102));
        jmiRemoveGast.setText("Remoção");
        jmiRemoveGast.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 102), 6));
        jmiRemoveGast.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jmiRemoveGastMousePressed(evt);
            }
        });
        jmGasto.add(jmiRemoveGast);

        jmiAlteraGast.setBackground(new java.awt.Color(0, 153, 255));
        jmiAlteraGast.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jmiAlteraGast.setForeground(new java.awt.Color(255, 102, 102));
        jmiAlteraGast.setText("Alteração");
        jmiAlteraGast.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 102), 6));
        jmiAlteraGast.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jmiAlteraGastMousePressed(evt);
            }
        });
        jmGasto.add(jmiAlteraGast);

        jmiListaGast.setBackground(new java.awt.Color(0, 153, 255));
        jmiListaGast.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jmiListaGast.setForeground(new java.awt.Color(255, 102, 102));
        jmiListaGast.setText("Listagem");
        jmiListaGast.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 102), 6));
        jmiListaGast.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jmiListaGastMousePressed(evt);
            }
        });
        jmGasto.add(jmiListaGast);

        jmItemGasto.setBackground(new java.awt.Color(51, 255, 51));
        jmItemGasto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0), 5));
        jmItemGasto.setForeground(new java.awt.Color(51, 0, 51));
        jmItemGasto.setText("Ítens");
        jmItemGasto.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N

        jmiRemoveItem.setBackground(new java.awt.Color(0, 153, 255));
        jmiRemoveItem.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jmiRemoveItem.setForeground(new java.awt.Color(255, 102, 102));
        jmiRemoveItem.setText("Remoção");
        jmiRemoveItem.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 102), 6));
        jmiRemoveItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jmiRemoveItemMousePressed(evt);
            }
        });
        jmItemGasto.add(jmiRemoveItem);

        jmiAlteraItem.setBackground(new java.awt.Color(0, 153, 255));
        jmiAlteraItem.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jmiAlteraItem.setForeground(new java.awt.Color(255, 102, 102));
        jmiAlteraItem.setText("Alteração");
        jmiAlteraItem.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 102), 6));
        jmiAlteraItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jmiAlteraItemMousePressed(evt);
            }
        });
        jmItemGasto.add(jmiAlteraItem);

        jmiListaItem.setBackground(new java.awt.Color(0, 153, 255));
        jmiListaItem.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jmiListaItem.setForeground(new java.awt.Color(255, 102, 102));
        jmiListaItem.setText("Listagem");
        jmiListaItem.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 102), 6));
        jmiListaItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jmiListaItemMousePressed(evt);
            }
        });
        jmItemGasto.add(jmiListaItem);

        jmGasto.add(jmItemGasto);

        jmDivida.setBackground(new java.awt.Color(51, 255, 51));
        jmDivida.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0), 5));
        jmDivida.setForeground(new java.awt.Color(51, 0, 51));
        jmDivida.setText("Dívida");
        jmDivida.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N

        jmiCadastroDiv.setBackground(new java.awt.Color(0, 153, 255));
        jmiCadastroDiv.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jmiCadastroDiv.setForeground(new java.awt.Color(255, 102, 102));
        jmiCadastroDiv.setText("Cadastro");
        jmiCadastroDiv.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 102), 6));
        jmiCadastroDiv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jmiCadastroDivMousePressed(evt);
            }
        });
        jmDivida.add(jmiCadastroDiv);

        jmiRemoveDiv.setBackground(new java.awt.Color(0, 153, 255));
        jmiRemoveDiv.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jmiRemoveDiv.setForeground(new java.awt.Color(255, 102, 102));
        jmiRemoveDiv.setText("Remoção");
        jmiRemoveDiv.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 102), 6));
        jmiRemoveDiv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jmiRemoveDivMousePressed(evt);
            }
        });
        jmDivida.add(jmiRemoveDiv);

        jmiAlteraDiv.setBackground(new java.awt.Color(0, 153, 255));
        jmiAlteraDiv.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jmiAlteraDiv.setForeground(new java.awt.Color(255, 102, 102));
        jmiAlteraDiv.setText("Alteração");
        jmiAlteraDiv.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 102), 6));
        jmiAlteraDiv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jmiAlteraDivMousePressed(evt);
            }
        });
        jmDivida.add(jmiAlteraDiv);

        jmiListaDiv.setBackground(new java.awt.Color(0, 153, 255));
        jmiListaDiv.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jmiListaDiv.setForeground(new java.awt.Color(255, 102, 102));
        jmiListaDiv.setText("Listagem");
        jmiListaDiv.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 102), 6));
        jmiListaDiv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jmiListaDivMousePressed(evt);
            }
        });
        jmDivida.add(jmiListaDiv);

        jmGasto.add(jmDivida);

        jmEntradaSaida.add(jmGasto);

        jmEntradaCapital.setBackground(new java.awt.Color(51, 255, 51));
        jmEntradaCapital.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0), 5));
        jmEntradaCapital.setForeground(new java.awt.Color(51, 0, 51));
        jmEntradaCapital.setText("Capital");
        jmEntradaCapital.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N

        jmiCadastroEntradaCapital.setBackground(new java.awt.Color(0, 153, 255));
        jmiCadastroEntradaCapital.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jmiCadastroEntradaCapital.setForeground(new java.awt.Color(255, 102, 102));
        jmiCadastroEntradaCapital.setText("Cadastro");
        jmiCadastroEntradaCapital.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 102), 6));
        jmiCadastroEntradaCapital.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jmiCadastroEntradaCapitalMousePressed(evt);
            }
        });
        jmEntradaCapital.add(jmiCadastroEntradaCapital);

        jmiRemoveEntradaCapital.setBackground(new java.awt.Color(0, 153, 255));
        jmiRemoveEntradaCapital.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jmiRemoveEntradaCapital.setForeground(new java.awt.Color(255, 102, 102));
        jmiRemoveEntradaCapital.setText("Remoção");
        jmiRemoveEntradaCapital.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 102), 6));
        jmiRemoveEntradaCapital.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jmiRemoveEntradaCapitalMousePressed(evt);
            }
        });
        jmEntradaCapital.add(jmiRemoveEntradaCapital);

        jmiAlteraEntradaCapital.setBackground(new java.awt.Color(0, 153, 255));
        jmiAlteraEntradaCapital.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jmiAlteraEntradaCapital.setForeground(new java.awt.Color(255, 102, 102));
        jmiAlteraEntradaCapital.setText("Alteração");
        jmiAlteraEntradaCapital.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 102), 6));
        jmiAlteraEntradaCapital.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jmiAlteraEntradaCapitalMousePressed(evt);
            }
        });
        jmEntradaCapital.add(jmiAlteraEntradaCapital);

        jmiListaEntradaCapital.setBackground(new java.awt.Color(0, 153, 255));
        jmiListaEntradaCapital.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jmiListaEntradaCapital.setForeground(new java.awt.Color(255, 102, 102));
        jmiListaEntradaCapital.setText("Listagem");
        jmiListaEntradaCapital.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 102), 6));
        jmiListaEntradaCapital.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jmiListaEntradaCapitalMousePressed(evt);
            }
        });
        jmEntradaCapital.add(jmiListaEntradaCapital);

        jmEntradaSaida.add(jmEntradaCapital);

        jmMetas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0), 5));
        jmMetas.setText("Metas");
        jmMetas.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N

        jmiCadastro.setBackground(new java.awt.Color(51, 255, 51));
        jmiCadastro.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jmiCadastro.setForeground(new java.awt.Color(0, 51, 51));
        jmiCadastro.setText("Cadastro");
        jmiCadastro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0), 5));
        jmiCadastro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jmiCadastroMousePressed(evt);
            }
        });
        jmMetas.add(jmiCadastro);

        jmiRemocao.setBackground(new java.awt.Color(51, 255, 51));
        jmiRemocao.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jmiRemocao.setForeground(new java.awt.Color(0, 51, 51));
        jmiRemocao.setText("Remoção");
        jmiRemocao.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0), 5));
        jmiRemocao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jmiRemocaoMousePressed(evt);
            }
        });
        jmMetas.add(jmiRemocao);

        jmiAlteracao.setBackground(new java.awt.Color(51, 255, 51));
        jmiAlteracao.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jmiAlteracao.setForeground(new java.awt.Color(0, 51, 51));
        jmiAlteracao.setText("Alteração");
        jmiAlteracao.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0), 5));
        jmiAlteracao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jmiAlteracaoMousePressed(evt);
            }
        });
        jmMetas.add(jmiAlteracao);

        jmiListagemMetas.setBackground(new java.awt.Color(51, 255, 51));
        jmiListagemMetas.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jmiListagemMetas.setForeground(new java.awt.Color(0, 51, 51));
        jmiListagemMetas.setText("Listagem");
        jmiListagemMetas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0), 5));
        jmiListagemMetas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jmiListagemMetasMousePressed(evt);
            }
        });
        jmMetas.add(jmiListagemMetas);

        jmEntradaSaida.add(jmMetas);

        jmbPrincipal.add(jmEntradaSaida);

        jmCatalogo.setBackground(new java.awt.Color(51, 255, 51));
        jmCatalogo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0), 5));
        jmCatalogo.setForeground(new java.awt.Color(51, 0, 51));
        jmCatalogo.setText("Catálogo ");
        jmCatalogo.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N

        jmiCadastroCat.setBackground(new java.awt.Color(0, 153, 255));
        jmiCadastroCat.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jmiCadastroCat.setForeground(new java.awt.Color(255, 102, 102));
        jmiCadastroCat.setText("Cadastro");
        jmiCadastroCat.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 102), 6));
        jmiCadastroCat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jmiCadastroCatMousePressed(evt);
            }
        });
        jmCatalogo.add(jmiCadastroCat);

        jmiRemoveCat.setBackground(new java.awt.Color(0, 153, 255));
        jmiRemoveCat.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jmiRemoveCat.setForeground(new java.awt.Color(255, 102, 102));
        jmiRemoveCat.setText("Remoção");
        jmiRemoveCat.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 102), 6));
        jmiRemoveCat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jmiRemoveCatMousePressed(evt);
            }
        });
        jmCatalogo.add(jmiRemoveCat);

        jmiAlteraCat.setBackground(new java.awt.Color(0, 153, 255));
        jmiAlteraCat.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jmiAlteraCat.setForeground(new java.awt.Color(255, 102, 102));
        jmiAlteraCat.setText("Alteração");
        jmiAlteraCat.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 102), 6));
        jmiAlteraCat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jmiAlteraCatMousePressed(evt);
            }
        });
        jmCatalogo.add(jmiAlteraCat);

        jmiListaCat.setBackground(new java.awt.Color(0, 153, 255));
        jmiListaCat.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jmiListaCat.setForeground(new java.awt.Color(255, 102, 102));
        jmiListaCat.setText("Listagem");
        jmiListaCat.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 102), 6));
        jmiListaCat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jmiListaCatMousePressed(evt);
            }
        });
        jmCatalogo.add(jmiListaCat);

        jmbPrincipal.add(jmCatalogo);

        jmPessoa.setBackground(new java.awt.Color(51, 255, 51));
        jmPessoa.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0), 5));
        jmPessoa.setForeground(new java.awt.Color(51, 0, 51));
        jmPessoa.setText("Pessoa");
        jmPessoa.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N

        jmiCadastroPess.setBackground(new java.awt.Color(0, 153, 255));
        jmiCadastroPess.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jmiCadastroPess.setForeground(new java.awt.Color(255, 102, 102));
        jmiCadastroPess.setText("Cadastro");
        jmiCadastroPess.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 102), 6));
        jmiCadastroPess.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jmiCadastroPessMousePressed(evt);
            }
        });
        jmPessoa.add(jmiCadastroPess);

        jmiRemovePess.setBackground(new java.awt.Color(0, 153, 255));
        jmiRemovePess.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jmiRemovePess.setForeground(new java.awt.Color(255, 102, 102));
        jmiRemovePess.setText("Remoção");
        jmiRemovePess.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 102), 6));
        jmiRemovePess.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jmiRemovePessMousePressed(evt);
            }
        });
        jmPessoa.add(jmiRemovePess);

        jmiAlteraPess.setBackground(new java.awt.Color(0, 153, 255));
        jmiAlteraPess.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jmiAlteraPess.setForeground(new java.awt.Color(255, 102, 102));
        jmiAlteraPess.setText("Alteração");
        jmiAlteraPess.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 102), 6));
        jmiAlteraPess.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jmiAlteraPessMousePressed(evt);
            }
        });
        jmPessoa.add(jmiAlteraPess);

        jmiListaPess.setBackground(new java.awt.Color(0, 153, 255));
        jmiListaPess.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jmiListaPess.setForeground(new java.awt.Color(255, 102, 102));
        jmiListaPess.setText("Listagem");
        jmiListaPess.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 102), 6));
        jmiListaPess.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jmiListaPessMousePressed(evt);
            }
        });
        jmPessoa.add(jmiListaPess);

        jmLogin.setBackground(new java.awt.Color(51, 255, 51));
        jmLogin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0), 5));
        jmLogin.setForeground(new java.awt.Color(51, 0, 51));
        jmLogin.setText("Login");
        jmLogin.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N

        jmiCadastroLog.setBackground(new java.awt.Color(0, 153, 255));
        jmiCadastroLog.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jmiCadastroLog.setForeground(new java.awt.Color(255, 102, 102));
        jmiCadastroLog.setText("Cadastro");
        jmiCadastroLog.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 102), 6));
        jmiCadastroLog.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jmiCadastroLogMousePressed(evt);
            }
        });
        jmLogin.add(jmiCadastroLog);

        jmiRemoveLog.setBackground(new java.awt.Color(0, 153, 255));
        jmiRemoveLog.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jmiRemoveLog.setForeground(new java.awt.Color(255, 102, 102));
        jmiRemoveLog.setText("Remoção");
        jmiRemoveLog.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 102), 6));
        jmiRemoveLog.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jmiRemoveLogMousePressed(evt);
            }
        });
        jmLogin.add(jmiRemoveLog);

        jmiAlteraLog.setBackground(new java.awt.Color(0, 153, 255));
        jmiAlteraLog.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jmiAlteraLog.setForeground(new java.awt.Color(255, 102, 102));
        jmiAlteraLog.setText("Alteração");
        jmiAlteraLog.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 102), 6));
        jmiAlteraLog.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jmiAlteraLogMousePressed(evt);
            }
        });
        jmLogin.add(jmiAlteraLog);

        jmiListaLog.setBackground(new java.awt.Color(0, 153, 255));
        jmiListaLog.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jmiListaLog.setForeground(new java.awt.Color(255, 102, 102));
        jmiListaLog.setText("Listagem");
        jmiListaLog.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 102), 6));
        jmiListaLog.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jmiListaLogMousePressed(evt);
            }
        });
        jmLogin.add(jmiListaLog);

        jmPessoa.add(jmLogin);

        jmFornecedor.setBackground(new java.awt.Color(51, 255, 51));
        jmFornecedor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0), 5));
        jmFornecedor.setForeground(new java.awt.Color(51, 0, 51));
        jmFornecedor.setText("Fornecedor");
        jmFornecedor.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N

        jmiCadastroFornecedor.setBackground(new java.awt.Color(0, 153, 255));
        jmiCadastroFornecedor.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jmiCadastroFornecedor.setForeground(new java.awt.Color(255, 102, 102));
        jmiCadastroFornecedor.setText("Cadastro");
        jmiCadastroFornecedor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 102), 6));
        jmiCadastroFornecedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jmiCadastroFornecedorMousePressed(evt);
            }
        });
        jmFornecedor.add(jmiCadastroFornecedor);

        jmiRemoveFornecedor.setBackground(new java.awt.Color(0, 153, 255));
        jmiRemoveFornecedor.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jmiRemoveFornecedor.setForeground(new java.awt.Color(255, 102, 102));
        jmiRemoveFornecedor.setText("Remoção");
        jmiRemoveFornecedor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 102), 6));
        jmiRemoveFornecedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jmiRemoveFornecedorMousePressed(evt);
            }
        });
        jmFornecedor.add(jmiRemoveFornecedor);

        jmiAlteraFornecedor.setBackground(new java.awt.Color(0, 153, 255));
        jmiAlteraFornecedor.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jmiAlteraFornecedor.setForeground(new java.awt.Color(255, 102, 102));
        jmiAlteraFornecedor.setText("Alteração");
        jmiAlteraFornecedor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 102), 6));
        jmiAlteraFornecedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jmiAlteraFornecedorMousePressed(evt);
            }
        });
        jmFornecedor.add(jmiAlteraFornecedor);

        jmiListaFornecedor.setBackground(new java.awt.Color(0, 153, 255));
        jmiListaFornecedor.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jmiListaFornecedor.setForeground(new java.awt.Color(255, 102, 102));
        jmiListaFornecedor.setText("Listagem");
        jmiListaFornecedor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 102), 6));
        jmiListaFornecedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jmiListaFornecedorMousePressed(evt);
            }
        });
        jmFornecedor.add(jmiListaFornecedor);

        jmPessoa.add(jmFornecedor);

        jmbPrincipal.add(jmPessoa);

        jmSair.setBackground(new java.awt.Color(51, 255, 51));
        jmSair.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0), 5));
        jmSair.setForeground(new java.awt.Color(51, 0, 51));
        jmSair.setText("Sair");
        jmSair.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jmSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jmSairMousePressed(evt);
            }
        });
        jmbPrincipal.add(jmSair);

        setJMenuBar(jmbPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jspFundo, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jspFundo, javax.swing.GroupLayout.DEFAULT_SIZE, 712, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiAnaliseMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmiAnaliseMousePressed
         //Vai para o frame desejado e fecha o atual.
        
        AnalisaGastos.main(argumento, jtxtUsuario.getText());
                
        MenuPrincipal.this.dispose();
        
    }//GEN-LAST:event_jmiAnaliseMousePressed

    private void jmiCadastroGastMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmiCadastroGastMousePressed
         //Vai para o frame desejado e fecha o atual.
        
        CadastroGasto.main(argumento, jtxtUsuario.getText());
                
        MenuPrincipal.this.dispose();
        
    }//GEN-LAST:event_jmiCadastroGastMousePressed

    private void jmiRemoveGastMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmiRemoveGastMousePressed
        //Vai para o frame desejado e fecha o atual.
        
        RemoverGasto.main(argumento, jtxtUsuario.getText());
                
        MenuPrincipal.this.dispose();
        
    }//GEN-LAST:event_jmiRemoveGastMousePressed

    private void jmiAlteraGastMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmiAlteraGastMousePressed
        //Vai para o frame desejado e fecha o atual.
        
        AlteraGasto.main(argumento, jtxtUsuario.getText());
                
        MenuPrincipal.this.dispose();
        
    }//GEN-LAST:event_jmiAlteraGastMousePressed

    private void jmiListaGastMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmiListaGastMousePressed
        //Vai para o frame desejado e fecha o atual.
        
        ListagemGasto.main(argumento, null,null, "", true , jtxtUsuario.getText(),"Registros de gastos.", null, null);
                
        MenuPrincipal.this.dispose();
        
    }//GEN-LAST:event_jmiListaGastMousePressed

    private void jmiCadastroEntradaCapitalMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmiCadastroEntradaCapitalMousePressed
        //Vai para o frame desejado e fecha o atual.
        
        CadastroEntradaCapital.main(argumento, jtxtUsuario.getText());
                
        MenuPrincipal.this.dispose();
        
    }//GEN-LAST:event_jmiCadastroEntradaCapitalMousePressed

    private void jmiRemoveEntradaCapitalMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmiRemoveEntradaCapitalMousePressed
        //Vai para o frame desejado e fecha o atual.
        
        RemoverEntradaCapital.main(argumento, jtxtUsuario.getText());
                
        MenuPrincipal.this.dispose(); 
        
    }//GEN-LAST:event_jmiRemoveEntradaCapitalMousePressed

    private void jmiRemoveItemMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmiRemoveItemMousePressed
        //Vai para o frame desejado e fecha o atual.
        
        RemoverItem.main(argumento, jtxtUsuario.getText());
                
        MenuPrincipal.this.dispose();
        
    }//GEN-LAST:event_jmiRemoveItemMousePressed

    private void jmiAlteraItemMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmiAlteraItemMousePressed
        //Vai para o frame desejado e fecha o atual.
        
        AlteraItem.main(argumento, jtxtUsuario.getText());
                
        MenuPrincipal.this.dispose();
        
    }//GEN-LAST:event_jmiAlteraItemMousePressed

    private void jmiListaItemMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmiListaItemMousePressed
        //Vai para o frame desejado e fecha o atual.
        
        ListagemItem.main(argumento,null,null,null,null, "", true, "Registros de ítens.", jtxtUsuario.getText());
                
        MenuPrincipal.this.dispose();
        
    }//GEN-LAST:event_jmiListaItemMousePressed

    private void jmiCadastroDivMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmiCadastroDivMousePressed
        //Vai para o frame desejado e fecha o atual.
        
        CadastroDivida.main(argumento,  jtxtUsuario.getText());
                
        MenuPrincipal.this.dispose();
        
    }//GEN-LAST:event_jmiCadastroDivMousePressed

    private void jmiRemoveDivMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmiRemoveDivMousePressed
        //Vai para o frame desejado e fecha o atual.
        
        RemoverDivida.main(argumento, jtxtUsuario.getText());
                
        MenuPrincipal.this.dispose();
        
    }//GEN-LAST:event_jmiRemoveDivMousePressed

    private void jmiAlteraDivMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmiAlteraDivMousePressed
        //Vai para o frame desejado e fecha o atual.
        
        AlteraDivida.main(argumento, jtxtUsuario.getText());
                
        MenuPrincipal.this.dispose();
        
    }//GEN-LAST:event_jmiAlteraDivMousePressed

    private void jmiListaDivMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmiListaDivMousePressed
        //Vai para o frame desejado e fecha o atual.
        
        ListagemDivida.main(argumento, null,null, "", true, jtxtUsuario.getText(), "Registros de dívida.");
                
        MenuPrincipal.this.dispose();
        
    }//GEN-LAST:event_jmiListaDivMousePressed

    private void jmiAlteraEntradaCapitalMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmiAlteraEntradaCapitalMousePressed
        //Vai para o frame desejado e fecha o atual.
        
        AlteraEntradaCapital.main(argumento, jtxtUsuario.getText());
                
        MenuPrincipal.this.dispose();
        
    }//GEN-LAST:event_jmiAlteraEntradaCapitalMousePressed

    private void jmiListaEntradaCapitalMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmiListaEntradaCapitalMousePressed
        //Vai para o frame desejado e fecha o atual.
        
        ListagemEntradaCapital.main(argumento, null,null,null,null,null, "", true, jtxtUsuario.getText(), "Registros de entrada de capital.");
                
        MenuPrincipal.this.dispose();
        
    }//GEN-LAST:event_jmiListaEntradaCapitalMousePressed

    private void jmiCadastroCatMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmiCadastroCatMousePressed
        //Vai para o frame desejado e fecha o atual.
        
        CadastroCatalogo.main(argumento, jtxtUsuario.getText());
                
        MenuPrincipal.this.dispose();
        
    }//GEN-LAST:event_jmiCadastroCatMousePressed

    private void jmiRemoveCatMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmiRemoveCatMousePressed
        //Vai para o frame desejado e fecha o atual.
        
        RemoverCatalogo.main(argumento, jtxtUsuario.getText());
                
        MenuPrincipal.this.dispose();
        
    }//GEN-LAST:event_jmiRemoveCatMousePressed

    private void jmiAlteraCatMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmiAlteraCatMousePressed
        //Vai para o frame desejado e fecha o atual.
        
        AlteraCatalogo.main(argumento, jtxtUsuario.getText());
                
        MenuPrincipal.this.dispose();
        
    }//GEN-LAST:event_jmiAlteraCatMousePressed

    private void jmiListaCatMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmiListaCatMousePressed
       //Vai para o frame desejado e fecha o atual.
        
        ListagemCatalogo.main(argumento, null,null,null, "", true, jtxtUsuario.getText(), "Registros de produto.");
                
        MenuPrincipal.this.dispose();
        
    }//GEN-LAST:event_jmiListaCatMousePressed

    private void jmiCadastroPessMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmiCadastroPessMousePressed
        //Vai para o frame desejado e fecha o atual.
        
        CadastroPessoa.main(argumento, jtxtUsuario.getText());
                
        MenuPrincipal.this.dispose();
        
    }//GEN-LAST:event_jmiCadastroPessMousePressed

    private void jmiRemovePessMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmiRemovePessMousePressed
        //Vai para o frame desejado e fecha o atual.
        
        RemoverPessoa.main(argumento, jtxtUsuario.getText());
                
        MenuPrincipal.this.dispose();
        
    }//GEN-LAST:event_jmiRemovePessMousePressed

    private void jmiAlteraPessMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmiAlteraPessMousePressed
        //Vai para o frame desejado e fecha o atual.
        
        AlteraPessoa.main(argumento, jtxtUsuario.getText());
                
        MenuPrincipal.this.dispose();
        
        
    }//GEN-LAST:event_jmiAlteraPessMousePressed

    private void jmiListaPessMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmiListaPessMousePressed
        //Vai para o frame desejado e fecha o atual.
        
        ListagemPessoa.main(argumento, null,null, "", true, jtxtUsuario.getText(), "Registros de pessoa.");
                
        MenuPrincipal.this.dispose();
        
    }//GEN-LAST:event_jmiListaPessMousePressed

    private void jmiCadastroLogMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmiCadastroLogMousePressed
        //Vai para o frame desejado e fecha o atual.
        
        CadastroLogin.main(argumento, jtxtUsuario.getText());
                
        MenuPrincipal.this.dispose();
        
    }//GEN-LAST:event_jmiCadastroLogMousePressed

    private void jmiRemoveLogMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmiRemoveLogMousePressed
        //Vai para o frame desejado e fecha o atual.
        
        RemoverLogin.main(argumento, jtxtUsuario.getText());
                
        MenuPrincipal.this.dispose();
        
    }//GEN-LAST:event_jmiRemoveLogMousePressed

    private void jmiAlteraLogMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmiAlteraLogMousePressed
        //Vai para o frame desejado e fecha o atual.
        
        AlteraLogin.main(argumento, jtxtUsuario.getText());
                
        MenuPrincipal.this.dispose();
        
    }//GEN-LAST:event_jmiAlteraLogMousePressed

    private void jmiListaLogMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmiListaLogMousePressed
        //Vai para o frame desejado e fecha o atual.
        
        ListagemLogin.main(argumento, null,null, "", true, "Registros de usuário.", jtxtUsuario.getText());
                
        MenuPrincipal.this.dispose();
        
    }//GEN-LAST:event_jmiListaLogMousePressed

    private void jmiBalanceteSelecionadoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmiBalanceteSelecionadoMousePressed
        // Vai para a tela de login e fecha o frame atual.
        
        BalanceteSelecionado.main(argumento, jtxtUsuario.getText());
        
        MenuPrincipal.this.dispose();
        
    }//GEN-LAST:event_jmiBalanceteSelecionadoMousePressed

    private void jmiAlteracaoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmiAlteracaoMousePressed
         // Vai para a tela de alteração de metas e fecha o frame atual.
        
        AlteraMeta.main(argumento, jtxtUsuario.getText());
        
        MenuPrincipal.this.dispose();
        
    }//GEN-LAST:event_jmiAlteracaoMousePressed

    private void jmiListagemMetasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmiListagemMetasMousePressed
        // Vai para a tela de listagem de Metas e fecha o frame atual.
        
        ListagemMeta.main(argumento, null, null, null, " ", true, jtxtUsuario.getText(), "Registros de metas.");
        
        MenuPrincipal.this.dispose();
        
    }//GEN-LAST:event_jmiListagemMetasMousePressed

    private void jmiRemocaoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmiRemocaoMousePressed
        // Vai para a tela de remoção de metas e fecha o frame atual.
        
        RemoverMeta.main(argumento, jtxtUsuario.getText());
        
        MenuPrincipal.this.dispose();
        
    }//GEN-LAST:event_jmiRemocaoMousePressed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // Defini que opções que aparecem para usuário ver.
        
        if(new Funcoes().getTipoUsuario(jtxtUsuario.getText()).toString().compareTo("usuario") == 0)
            
        {
            
            jmiRemovePess.setVisible(false);
            
            jmiCadastroPess.setVisible(false);
            
            jmLogin.setVisible(false);
            
            jmiCadastroFornecedor.setVisible(false);
            
            jmFornecedor.setVisible(true);
           
            
        }
        
        if(new Funcoes().getTipoUsuario(jtxtUsuario.getText()).toString().compareTo("administrador") == 0)
            
        {
            
            jmiCadastroFornecedor.setVisible(false);
            
            jmiAlteraFornecedor.setVisible(false);
            
            jmFornecedor.setVisible(true);
           
            
        }
        
    }//GEN-LAST:event_formWindowActivated

    private void jmiCadastroMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmiCadastroMousePressed
        // Vai para a tela de cadastro de metas e fecha o frame atual.
        
        CadastroMetas.main(argumento, jtxtUsuario.getText());
        
        MenuPrincipal.this.dispose();
        
    }//GEN-LAST:event_jmiCadastroMousePressed

    private void jmSairMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmSairMousePressed
          // Vai para a tela de login e fecha o frame atual.
        
        Login.main(argumento);
        
        MenuPrincipal.this.dispose();
        
    }//GEN-LAST:event_jmSairMousePressed

    private void jmiCadastroFornecedorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmiCadastroFornecedorMousePressed
        // Vai para a tela de cadastro de fornecedores e fechao frame atual.
        
        CadastroFornecedor.main(argumento, jtxtUsuario.getText());
        
        MenuPrincipal.this.dispose();
        
    }//GEN-LAST:event_jmiCadastroFornecedorMousePressed

    private void jmiListaFornecedorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmiListaFornecedorMousePressed
        // Vai para a tela de registros de fornecedores e fecha o frame atual.
        
        ListagemFornecedor.main(argumento, null,null, "", true, "Registros de fornecedores.", jtxtUsuario.getText());
                
        MenuPrincipal.this.dispose();
        
    }//GEN-LAST:event_jmiListaFornecedorMousePressed

    private void jmiAlteraFornecedorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmiAlteraFornecedorMousePressed
        // Vai para a tela de alteração de fornecedores e fecha o frame atual.
        
        AlteraFornecedor.main(argumento, jtxtUsuario.getText());
        
        MenuPrincipal.this.dispose();
        
    }//GEN-LAST:event_jmiAlteraFornecedorMousePressed

    private void jmiRemoveFornecedorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmiRemoveFornecedorMousePressed
        // Vai para a tela de remoção de registro de fornecedor e fecha o frame atual.
        
        RemoverFornecedor.main(argumento, jtxtUsuario.getText());
        
        MenuPrincipal.this.dispose();
        
    }//GEN-LAST:event_jmiRemoveFornecedorMousePressed

    /**
     * @param argumento the command line arguments
     */
    public static void main(String argumento[], String u) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
                
                jtxtUsuario.setText(u);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jmCatalogo;
    private javax.swing.JMenu jmDivida;
    private javax.swing.JMenu jmEntradaCapital;
    private javax.swing.JMenu jmEntradaSaida;
    private javax.swing.JMenu jmFornecedor;
    private javax.swing.JMenu jmGasto;
    private javax.swing.JMenu jmItemGasto;
    private javax.swing.JMenu jmLogin;
    private javax.swing.JMenu jmMetas;
    private javax.swing.JMenu jmPessoa;
    private javax.swing.JMenu jmSair;
    private javax.swing.JMenuBar jmbPrincipal;
    private javax.swing.JMenuItem jmiAlteraCat;
    private javax.swing.JMenuItem jmiAlteraDiv;
    private javax.swing.JMenuItem jmiAlteraEntradaCapital;
    private javax.swing.JMenuItem jmiAlteraFornecedor;
    private javax.swing.JMenuItem jmiAlteraGast;
    private javax.swing.JMenuItem jmiAlteraItem;
    private javax.swing.JMenuItem jmiAlteraLog;
    private javax.swing.JMenuItem jmiAlteraPess;
    private javax.swing.JMenuItem jmiAlteracao;
    private javax.swing.JMenuItem jmiAnalise;
    private javax.swing.JMenuItem jmiBalanceteSelecionado;
    private javax.swing.JMenuItem jmiCadastro;
    private javax.swing.JMenuItem jmiCadastroCat;
    private javax.swing.JMenuItem jmiCadastroDiv;
    private javax.swing.JMenuItem jmiCadastroEntradaCapital;
    private javax.swing.JMenuItem jmiCadastroFornecedor;
    private javax.swing.JMenuItem jmiCadastroGast;
    private javax.swing.JMenuItem jmiCadastroLog;
    private javax.swing.JMenuItem jmiCadastroPess;
    private javax.swing.JMenuItem jmiListaCat;
    private javax.swing.JMenuItem jmiListaDiv;
    private javax.swing.JMenuItem jmiListaEntradaCapital;
    private javax.swing.JMenuItem jmiListaFornecedor;
    private javax.swing.JMenuItem jmiListaGast;
    private javax.swing.JMenuItem jmiListaItem;
    private javax.swing.JMenuItem jmiListaLog;
    private javax.swing.JMenuItem jmiListaPess;
    private javax.swing.JMenuItem jmiListagemMetas;
    private javax.swing.JMenuItem jmiRemocao;
    private javax.swing.JMenuItem jmiRemoveCat;
    private javax.swing.JMenuItem jmiRemoveDiv;
    private javax.swing.JMenuItem jmiRemoveEntradaCapital;
    private javax.swing.JMenuItem jmiRemoveFornecedor;
    private javax.swing.JMenuItem jmiRemoveGast;
    private javax.swing.JMenuItem jmiRemoveItem;
    private javax.swing.JMenuItem jmiRemoveLog;
    private javax.swing.JMenuItem jmiRemovePess;
    private javax.swing.JPanel jpBase;
    private javax.swing.JScrollPane jspFundo;
    private static javax.swing.JTextField jtxtDataHora;
    private static javax.swing.JTextField jtxtUsuario;
    // End of variables declaration//GEN-END:variables
}
