/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package doug;

/**
 *
 * @author DOUGLASFERREIRAG
 */
public class PoderesUsuario extends javax.swing.JFrame {

    /**
     * Creates new form tipoUsuario
     */
    
    private static javax.swing.JTextField jtxtResult;
    
    private static String titulo,temp;
    
    public PoderesUsuario() {
        initComponents();
        
        jrbAdmin.setVisible(false);
        
        new Funcoes().executeTimer(jtxtDataHora, "dd/MM/yyyy hh:mm:ss");
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jspFundo = new javax.swing.JScrollPane();
        jpBase = new javax.swing.JPanel();
        jtxtRetorno = new javax.swing.JTextField();
        jrbAdmin = new javax.swing.JRadioButton();
        jrbUser = new javax.swing.JRadioButton();
        jtxtUsuario = new javax.swing.JTextField();
        jtxtDataHora = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jspFundo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));

        jtxtRetorno.setEditable(false);
        jtxtRetorno.setBackground(new java.awt.Color(0, 0, 255));
        jtxtRetorno.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jtxtRetorno.setForeground(new java.awt.Color(0, 51, 51));

        jrbAdmin.setBackground(new java.awt.Color(0, 0, 255));
        jrbAdmin.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jrbAdmin.setForeground(new java.awt.Color(0, 51, 51));
        jrbAdmin.setText("Adminsitrador");
        jrbAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jrbAdminMouseClicked(evt);
            }
        });

        jrbUser.setBackground(new java.awt.Color(0, 0, 255));
        jrbUser.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jrbUser.setForeground(new java.awt.Color(0, 51, 51));
        jrbUser.setText("Usuario");
        jrbUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jrbUserMouseClicked(evt);
            }
        });

        jtxtUsuario.setEditable(false);
        jtxtUsuario.setBackground(new java.awt.Color(0, 0, 255));
        jtxtUsuario.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jtxtUsuario.setForeground(new java.awt.Color(0, 51, 51));
        jtxtUsuario.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true), "Usuário", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 48), new java.awt.Color(0, 102, 102))); // NOI18N

        jtxtDataHora.setEditable(false);
        jtxtDataHora.setBackground(new java.awt.Color(0, 0, 255));
        jtxtDataHora.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jtxtDataHora.setForeground(new java.awt.Color(0, 51, 51));
        jtxtDataHora.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true), "Data e Hora", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 48), new java.awt.Color(0, 102, 102))); // NOI18N

        javax.swing.GroupLayout jpBaseLayout = new javax.swing.GroupLayout(jpBase);
        jpBase.setLayout(jpBaseLayout);
        jpBaseLayout.setHorizontalGroup(
            jpBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpBaseLayout.createSequentialGroup()
                .addGroup(jpBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpBaseLayout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addGroup(jpBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jrbUser, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jrbAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jpBaseLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jpBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtRetorno, javax.swing.GroupLayout.PREFERRED_SIZE, 832, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jpBaseLayout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addGroup(jpBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtxtDataHora, javax.swing.GroupLayout.PREFERRED_SIZE, 782, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtxtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 782, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(320, Short.MAX_VALUE))
        );
        jpBaseLayout.setVerticalGroup(
            jpBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpBaseLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jtxtRetorno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72)
                .addComponent(jrbAdmin)
                .addGap(18, 18, 18)
                .addComponent(jrbUser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 258, Short.MAX_VALUE)
                .addComponent(jtxtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addComponent(jtxtDataHora, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        jspFundo.setViewportView(jpBase);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jspFundo, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jspFundo, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jrbAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jrbAdminMouseClicked
        // Retorna o tipo administrador.

        jtxtRetorno.setText("administrador");
        
        jtxtResult.setText(jtxtRetorno.getText());
        
        dispose();
        
    }//GEN-LAST:event_jrbAdminMouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // Seta o título do formulário.
        
        this.setTitle(titulo);
        
       // Verifica se posso cadastrar alguém como admin.
        
        if( (Double.parseDouble(new Funcoes().retornar("SELECT COUNT(poderes) FROM login WHERE poderes = 'administrador'", "COUNT(poderes)", null).toString()) < 1) &&
                
             (temp.compareTo("cadastro") == 0))
            
            jrbAdmin.setVisible(true);
        
        else {
            
                if ( (new Funcoes().getTipoUsuario(jtxtUsuario.getText()).toString().compareTo("usuario") == 0) &&
                        (new Funcoes().retornar("SELECT COUNT(poderes) FROM login WHERE poderes = 'administrador'", "COUNT(poderes)", null) == null)
                     )
                    
                            jrbAdmin.setVisible(true);
            
        }
        
    }//GEN-LAST:event_formWindowActivated

    private void jrbUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jrbUserMouseClicked
         // Retorna o tipo usuário.

        jtxtRetorno.setText("usuario");
        
        jtxtResult.setText(jtxtRetorno.getText());
        
        dispose();
        

    }//GEN-LAST:event_jrbUserMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[], String user, javax.swing.JTextField jtxtReturn, String title, String t) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PoderesUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PoderesUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PoderesUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PoderesUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PoderesUsuario().setVisible(true);
                
                jtxtResult = jtxtReturn;
                
                jtxtUsuario.setText(user);
                
                titulo = title;
                
                temp = t;
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jpBase;
    private javax.swing.JRadioButton jrbAdmin;
    private javax.swing.JRadioButton jrbUser;
    private javax.swing.JScrollPane jspFundo;
    private static javax.swing.JTextField jtxtDataHora;
    private javax.swing.JTextField jtxtRetorno;
    private static javax.swing.JTextField jtxtUsuario;
    // End of variables declaration//GEN-END:variables
}
