/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package doug;

/**
 *
 * @author Douglas
 */



public class RemoverGasto extends javax.swing.JFrame {

    /**
     * Creates new form RemoverGasto
     */
    
    private String[] argumento;
    
    private boolean trava;
    
    
    
    
    public RemoverGasto() {
        initComponents();
        
        this.setExtendedState(MAXIMIZED_BOTH);
        
        trava = false;
        
        jmRemove.setVisible(false);
        
        new Funcoes().executeTimer(jtxtDataHora, "dd/MM/yyyy hh:mm:ss");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jspFundo = new javax.swing.JScrollPane();
        jpBase = new javax.swing.JPanel();
        jtxtCodigo = new javax.swing.JTextField();
        jtxtUsuario = new javax.swing.JTextField();
        jtxtDataHora = new javax.swing.JTextField();
        jmbMenu = new javax.swing.JMenuBar();
        jmRemove = new javax.swing.JMenu();
        jmMenu = new javax.swing.JMenu();
        jmLimpar = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Remover Gasto");
        setBackground(new java.awt.Color(255, 255, 102));
        setForeground(new java.awt.Color(153, 153, 0));
        setName("jfRemoveGasto"); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jpBase.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255), 5));

        jtxtCodigo.setEditable(false);
        jtxtCodigo.setBackground(new java.awt.Color(255, 255, 255));
        jtxtCodigo.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jtxtCodigo.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 0), 5), "Código", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 48))); // NOI18N
        jtxtCodigo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtCodigoMouseClicked(evt);
            }
        });

        jtxtUsuario.setEditable(false);
        jtxtUsuario.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jtxtUsuario.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 0), 5), "Usuário", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 48), new java.awt.Color(204, 204, 0))); // NOI18N

        jtxtDataHora.setEditable(false);
        jtxtDataHora.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jtxtDataHora.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 0), 5), "Data e Hora", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 48), new java.awt.Color(204, 204, 0))); // NOI18N

        javax.swing.GroupLayout jpBaseLayout = new javax.swing.GroupLayout(jpBase);
        jpBase.setLayout(jpBaseLayout);
        jpBaseLayout.setHorizontalGroup(
            jpBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpBaseLayout.createSequentialGroup()
                .addGroup(jpBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpBaseLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jtxtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 726, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpBaseLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jpBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtDataHora, javax.swing.GroupLayout.PREFERRED_SIZE, 1122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 1122, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(126, Short.MAX_VALUE))
        );
        jpBaseLayout.setVerticalGroup(
            jpBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpBaseLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jtxtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(270, 270, 270)
                .addComponent(jtxtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 456, Short.MAX_VALUE)
                .addComponent(jtxtDataHora, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jspFundo.setViewportView(jpBase);

        jmbMenu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 255, 204), 10));

        jmRemove.setBackground(new java.awt.Color(51, 51, 51));
        jmRemove.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0), 5));
        jmRemove.setForeground(new java.awt.Color(255, 51, 51));
        jmRemove.setText("Remover");
        jmRemove.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jmRemove.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmRemoveMouseClicked(evt);
            }
        });
        jmbMenu.add(jmRemove);

        jmMenu.setBackground(new java.awt.Color(51, 51, 51));
        jmMenu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0), 5));
        jmMenu.setForeground(new java.awt.Color(255, 51, 51));
        jmMenu.setText("Menu Principal");
        jmMenu.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jmMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmMenuMouseClicked(evt);
            }
        });
        jmbMenu.add(jmMenu);

        jmLimpar.setBackground(new java.awt.Color(51, 51, 51));
        jmLimpar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0), 5));
        jmLimpar.setForeground(new java.awt.Color(255, 51, 51));
        jmLimpar.setText("Limpar");
        jmLimpar.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jmLimpar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmLimparMouseClicked(evt);
            }
        });
        jmbMenu.add(jmLimpar);

        setJMenuBar(jmbMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jspFundo, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jspFundo, javax.swing.GroupLayout.DEFAULT_SIZE, 712, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmMenuMouseClicked
        // Vai para o menu principal e fecha o frame atual.

        
        MenuPrincipal.main(argumento, jtxtUsuario.getText());
        
        RemoverGasto.this.dispose();
        
    }//GEN-LAST:event_jmMenuMouseClicked

    private void jmLimparMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmLimparMouseClicked
        // Põe o form no modo default.

        jtxtCodigo.setText("");
        
        jmRemove.setVisible(false);
        
        trava = false;
   
        
    }//GEN-LAST:event_jmLimparMouseClicked

    private void jmRemoveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmRemoveMouseClicked
        // Trata da remoção e atualização de códigos.

       
        jmRemove.setVisible(false);
        
        String[][] parametro = new String[1][2];
        
        parametro[0][0] = "Double";
        
        parametro[0][1] = jtxtCodigo.getText();

        new Funcoes().executa("delete from gasto where codigo = ?",
                            parametro, "Remoção na tabela de gastos realizada com sucesso.");
        
        if(new Funcoes().retornar("select sum(total) from item where codigoGasto = ?", "sum(total)", parametro) != null)
        
            new Funcoes().executa("delete from item where codigoGasto = ?",
                                parametro, "Remoção na tabela de ítens realizada com sucesso. ");
       
        if( (new Funcoes().retornar("SELECT Max(codigo) "
            + "FROM gasto ","Max(codigo)",null) != null) && (Double.parseDouble(jtxtCodigo.getText()) < (Double)new Funcoes().retornar("SELECT Max(codigo) "
                            + "FROM gasto ","Max(codigo)",null)) )

            new Funcoes().executa( "update gasto set codigo = codigo - 1 where codigo > ? ", parametro," Atualização de códigos na tabela de gastos realizada com sucesso.");

        
        
     
    }//GEN-LAST:event_jmRemoveMouseClicked

    private void jtxtCodigoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtCodigoMouseClicked
        // Vai para a tabela de listagem de gastos.
        
        if(jtxtCodigo.getText().isEmpty() == true) 
        
                ListagemGasto.main(argumento, jtxtCodigo, null,"Retorno de código", false,jtxtUsuario.getText(),"Selecione o código do registro a ser deletado.", null,null);
        
    }//GEN-LAST:event_jtxtCodigoMouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // Verifica se posso liberar o botão remover.
        
        if((jtxtCodigo.getText().isEmpty() == false) && (trava == false)) {
            
            jmRemove.setVisible(true);
            
            trava = true;
            
        }
        
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[], String user) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RemoverGasto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RemoverGasto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RemoverGasto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RemoverGasto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RemoverGasto().setVisible(true);
                
                jtxtUsuario.setText(user);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jmLimpar;
    private javax.swing.JMenu jmMenu;
    private javax.swing.JMenu jmRemove;
    private javax.swing.JMenuBar jmbMenu;
    private javax.swing.JPanel jpBase;
    private javax.swing.JScrollPane jspFundo;
    private javax.swing.JTextField jtxtCodigo;
    private static javax.swing.JTextField jtxtDataHora;
    private static javax.swing.JTextField jtxtUsuario;
    // End of variables declaration//GEN-END:variables
}
