/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package doug;

import javax.swing.JOptionPane;

/**
 *
 * @author DOUGLASFERREIRAG
 */
public class RemoverFornecedor extends javax.swing.JFrame {

    /**
     * Creates new form RemoverPagamento
     */
    
    private String[] argumento;
 
    private boolean trava;
    
    public RemoverFornecedor() {
        initComponents();
        
         this.setExtendedState(MAXIMIZED_BOTH);
        
        trava = false;
        
        jmRemover.setVisible(false);
        
        new Funcoes().executeTimer(jtxtDataHora, "dd/MM/yyyy hh:mm:ss");
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jspFundo = new javax.swing.JScrollPane();
        jpBase = new javax.swing.JPanel();
        jtxtCodigo = new javax.swing.JTextField();
        jtxtUsuario = new javax.swing.JTextField();
        jtxtDataHora = new javax.swing.JTextField();
        jmbMenu = new javax.swing.JMenuBar();
        jmRemover = new javax.swing.JMenu();
        jmMenu = new javax.swing.JMenu();
        jmLimpar = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Remoção de registro de pagamento");
        setName("frmRemovePagamento"); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jpBase.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 0), 6, true));

        jtxtCodigo.setEditable(false);
        jtxtCodigo.setBackground(java.awt.Color.white);
        jtxtCodigo.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jtxtCodigo.setForeground(java.awt.Color.red);
        jtxtCodigo.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(java.awt.Color.darkGray, 5, true), "Código", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 48), new java.awt.Color(255, 51, 51))); // NOI18N
        jtxtCodigo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtCodigoMouseClicked(evt);
            }
        });

        jtxtUsuario.setEditable(false);
        jtxtUsuario.setBackground(java.awt.Color.white);
        jtxtUsuario.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jtxtUsuario.setForeground(java.awt.Color.red);
        jtxtUsuario.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(java.awt.Color.darkGray, 5, true), "Usuário", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 48), new java.awt.Color(255, 51, 51))); // NOI18N

        jtxtDataHora.setEditable(false);
        jtxtDataHora.setBackground(java.awt.Color.white);
        jtxtDataHora.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jtxtDataHora.setForeground(java.awt.Color.red);
        jtxtDataHora.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(java.awt.Color.darkGray, 5, true), "Data e Hora", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 48), new java.awt.Color(255, 51, 51))); // NOI18N

        javax.swing.GroupLayout jpBaseLayout = new javax.swing.GroupLayout(jpBase);
        jpBase.setLayout(jpBaseLayout);
        jpBaseLayout.setHorizontalGroup(
            jpBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpBaseLayout.createSequentialGroup()
                .addGroup(jpBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpBaseLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jtxtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 1122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpBaseLayout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(jtxtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 604, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpBaseLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jtxtDataHora, javax.swing.GroupLayout.PREFERRED_SIZE, 1122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(261, Short.MAX_VALUE))
        );
        jpBaseLayout.setVerticalGroup(
            jpBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpBaseLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jtxtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(338, 338, 338)
                .addComponent(jtxtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 569, Short.MAX_VALUE)
                .addComponent(jtxtDataHora, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        jspFundo.setViewportView(jpBase);

        jmbMenu.setBackground(java.awt.Color.white);
        jmbMenu.setBorder(new javax.swing.border.LineBorder(java.awt.Color.darkGray, 10, true));
        jmbMenu.setForeground(java.awt.Color.red);

        jmRemover.setBackground(java.awt.Color.white);
        jmRemover.setBorder(new javax.swing.border.LineBorder(java.awt.Color.darkGray, 10, true));
        jmRemover.setForeground(java.awt.Color.red);
        jmRemover.setText("Remover");
        jmRemover.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jmRemover.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmRemoverMouseClicked(evt);
            }
        });
        jmbMenu.add(jmRemover);

        jmMenu.setBackground(java.awt.Color.white);
        jmMenu.setBorder(new javax.swing.border.LineBorder(java.awt.Color.darkGray, 10, true));
        jmMenu.setForeground(java.awt.Color.red);
        jmMenu.setText("Menu Principal");
        jmMenu.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jmMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmMenuMouseClicked(evt);
            }
        });
        jmbMenu.add(jmMenu);

        jmLimpar.setBackground(java.awt.Color.white);
        jmLimpar.setBorder(new javax.swing.border.LineBorder(java.awt.Color.darkGray, 10, true));
        jmLimpar.setForeground(java.awt.Color.red);
        jmLimpar.setText("Limpar");
        jmLimpar.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jmLimpar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmLimparMouseClicked(evt);
            }
        });
        jmbMenu.add(jmLimpar);

        setJMenuBar(jmbMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jspFundo, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jspFundo, javax.swing.GroupLayout.DEFAULT_SIZE, 702, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmRemoverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmRemoverMouseClicked
        // Remoção do registro. Atualização da tabela.

        jmRemover.setVisible(false);

        String[][] parametro = new String[1][2];

        JOptionPane.showMessageDialog(null, " Deletando...", "System Message", JOptionPane.INFORMATION_MESSAGE);

        parametro[0][0] = "Double";

        parametro[0][1] = jtxtCodigo.getText();

        new Funcoes().executa("delete from fornecedor where codigo = ?",
            parametro, "Remoção na tabela de fornecedor realizada com sucesso.");

        if( (new Funcoes().retornar("SELECT Max(codigo) "
            + "FROM fornecedor ","Max(codigo)",null) != null) && (Double.parseDouble(jtxtCodigo.getText()) < (Double)new Funcoes().retornar("SELECT Max(codigo) "
            + "FROM fornecedor ","Max(codigo)",null)) )

            new Funcoes().executa( "update fornecedor set codigo = codigo - 1 where codigo > ? ", parametro,"Atualização de códigos na tabela de fornecedors realizada com sucesso.");

    }//GEN-LAST:event_jmRemoverMouseClicked

    private void jmMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmMenuMouseClicked
        // Vai para o menu principal e fecha o frame atual.

        MenuPrincipal.main(argumento, jtxtUsuario.getText());

        RemoverFornecedor.this.dispose();

    }//GEN-LAST:event_jmMenuMouseClicked

    private void jmLimparMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmLimparMouseClicked
        //Limpa o formulário.

        jtxtCodigo.setText("");

        jmRemover.setVisible(false);
        
        jmRemover.setVisible(false);
        
        trava = false;

    }//GEN-LAST:event_jmLimparMouseClicked

    private void jtxtCodigoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtCodigoMouseClicked
        // Seleciona o código da meta.

        if(jtxtCodigo.getText().isEmpty() == true)

            ListagemFornecedor.main(argumento, jtxtCodigo, null,  "Retorno de código",   false, "Selecione o código do registro  a ser removido.", jtxtUsuario.getText());

    }//GEN-LAST:event_jtxtCodigoMouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
         // Verifica se posso liberar o botão remover.
        
        if((jtxtCodigo.getText().isEmpty() == false) && (trava == false)) {
            
            jmRemover.setVisible(true);
            
            trava = true;
            
        }
        
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[], String user) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RemoverFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RemoverFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RemoverFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RemoverFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RemoverFornecedor().setVisible(true);
                
                jtxtUsuario.setText(user);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jmLimpar;
    private javax.swing.JMenu jmMenu;
    private javax.swing.JMenu jmRemover;
    private javax.swing.JMenuBar jmbMenu;
    private javax.swing.JPanel jpBase;
    private javax.swing.JScrollPane jspFundo;
    private javax.swing.JTextField jtxtCodigo;
    private static javax.swing.JTextField jtxtDataHora;
    private static javax.swing.JTextField jtxtUsuario;
    // End of variables declaration//GEN-END:variables
}
